const LABELS = ["مبتدأ", "خبر", "حرف جر", "مضاف", "مضاف إليه", "فعل", "فاعل", "مفعول"];

function card(arabicText, translation, transliteration = "") {
  return { arabicText, translation, transliteration };
}

function pair(left, right) {
  return { left, right };
}

function token(word, label, gloss) {
  return { word, label, gloss };
}

function exerciseSet(spec, lessonIndex) {
  const [first, second, third] = spec.examples;
  const buildTiles = third.arabicText.split(" ").reverse();
  const buildOptions = buildTiles.length >= 2 ? buildTiles : [third.arabicText, second.arabicText, first.arabicText];
  const specialType = spec.order >= 10 ? "CONVERSATION_BUILDER" : spec.order >= 4 ? "GRAMMAR_PARSE" : "MATCHING";
  const exercises = [
    {
      type: "TRUE_FALSE",
      prompt: `In this pattern, "${first.translation}" belongs to today's lesson focus.`,
      arabicText: first.arabicText,
      options: ["True", "False"],
      correctAnswer: "True",
    },
    {
      type: "TAP_TRANSLATION",
      prompt: "What does this Arabic mean?",
      arabicText: second.arabicText,
      options: [second.translation, first.translation, third.translation, spec.distractor],
      correctAnswer: second.translation,
    },
    {
      type: "FILL_BLANK",
      prompt: "Choose the missing Arabic word.",
      arabicText: `___ ${first.arabicText.split(" ").slice(1).join(" ")}`,
      options: [first.arabicText.split(" ")[0], second.arabicText.split(" ")[0], third.arabicText.split(" ")[0], spec.blankDistractor],
      correctAnswer: first.arabicText.split(" ")[0],
    },
    {
      type: "BUILD_SENTENCE",
      prompt: `Build: ${third.translation}`,
      arabicText: "",
      options: buildOptions,
      correctAnswer: third.arabicText,
    },
  ];

  if (specialType === "MATCHING") {
    const pairs = spec.examples.slice(0, 3).map((item) => pair(item.arabicText, item.translation));
    exercises.push({
      type: "MATCHING",
      prompt: "Match each Arabic pattern with its meaning.",
      pairs,
      options: pairs.map((item) => item.right).reverse(),
    });
  } else if (specialType === "GRAMMAR_PARSE") {
    exercises.push({
      type: "GRAMMAR_PARSE",
      prompt: "Label the role of each word in a sentence you have already seen.",
      arabicText: spec.parseText,
      parseTokens: spec.parseTokens,
      labels: LABELS,
    });
  } else {
    exercises.push({
      type: "CONVERSATION_BUILDER",
      prompt: "Choose the reply that completes the exchange.",
      conversation: [
        { speaker: "Yusuf", line: spec.conversation[0] },
        { speaker: "Ibrahim", line: "..." },
      ],
      options: [spec.conversation[1], spec.conversationDistractor, second.arabicText, third.arabicText],
      correctAnswer: spec.conversation[1],
    });
  }

  return exercises.map((exercise, index) => ({
    ...exercise,
    explanation: index === 0 ? "This quick check resets the pace before production." : "The answer follows the pattern you saw in Discover.",
    lessonBeat: lessonIndex,
  }));
}

function makeLesson(spec, lessonIndex, focus) {
  const rotatedExamples = [
    spec.examples[(lessonIndex - 1) % spec.examples.length],
    spec.examples[lessonIndex % spec.examples.length],
    spec.examples[(lessonIndex + 1) % spec.examples.length],
  ];
  const lessonSpec = { ...spec, examples: rotatedExamples };

  return {
    title: focus.title,
    titleAr: focus.titleAr,
    type: "VOCABULARY",
    xpReward: 10,
    content: {
      sourceFile: spec.sourceFile,
      lectureTitle: spec.title,
      focus: focus.title,
      ustadh_noor_tip_en: `${spec.noorTip} Look for ${spec.hook.highlightedWord} in ${spec.hook.ayahRef} tonight.`,
      ustadh_noor_tip_ur: spec.noorTipUr,
    },
    hook: {
      ayahAr: spec.hook.ayahAr,
      ayahRef: spec.hook.ayahRef,
      question: focus.hookQuestion,
    },
    discoverCards: rotatedExamples.map((item) => card(item.arabicText, item.translation, item.transliteration)),
    exercises: exerciseSet(lessonSpec, lessonIndex),
    revealText: `${focus.reveal} Classical scholars name this ${focus.grammarTerm}. You met the pattern first, then the label.`,
    revealAyah: {
      ayahAr: spec.hook.ayahAr,
      ayahRef: spec.hook.ayahRef,
      highlightedWord: spec.hook.highlightedWord,
    },
    fatihaProgressDelta: focus.fatihaProgressDelta ?? 1,
  };
}

function chapter(spec) {
  return {
    order: spec.order,
    title: spec.title,
    titleAr: spec.titleAr,
    description: spec.description,
    worldMapX: Number((0.08 + spec.order * 0.055).toFixed(2)),
    worldMapY: Number((0.12 + (spec.order % 5) * 0.14).toFixed(2)),
    isLocked: spec.order !== 1,
    lessons: spec.focuses.map((focus, index) => makeLesson(spec, index + 1, focus)),
  };
}

const specs = [
  {
    order: 1,
    sourceFile: "reader_lecture_01_haza_zalika.md",
    title: "This, That, What, Who",
    titleAr: "هٰذَا، ذٰلِكَ، مَا، مَنْ",
    description: "Pointing words and first questions from the Medina Reader.",
    hook: { ayahAr: "ذٰلِكَ الْكِتَابُ لَا رَيْبَ فِيهِ", ayahRef: "Al-Baqarah 2:2", highlightedWord: "ذٰلِكَ" },
    examples: [
      card("هٰذَا بَيْتٌ", "This is a house", "haadha baytun"),
      card("ذٰلِكَ كِتَابٌ", "That is a book", "dhaalika kitaabun"),
      card("مَا هٰذَا؟", "What is this?", "maa haadha"),
      card("مَنْ هٰذَا؟", "Who is this?", "man haadha"),
    ],
    parseText: "هٰذَا بَيْتٌ",
    parseTokens: [token("هٰذَا", "مبتدأ", "this"), token("بَيْتٌ", "خبر", "house")],
    conversation: ["مَا هٰذَا؟", "هٰذَا قَلَمٌ"],
    conversationDistractor: "ذٰلِكَ نَجْمٌ",
    distractor: "The book is new",
    blankDistractor: "أَيْنَ",
    noorTip: "You have already seen this pointing style at the opening of Al-Baqarah.",
    noorTipUr: "آج رات سورۃ البقرہ کی ابتدا میں ذٰلِكَ تلاش کریں۔",
    focuses: [
      { title: "Near Things", titleAr: "هٰذَا", grammarTerm: "اسم اشارہ", reveal: "You pointed to nearby things in Arabic without needing the word 'is'.", hookQuestion: "Why does Arabic say 'this house' and still mean 'this is a house'?" },
      { title: "Far Things", titleAr: "ذٰلِكَ", grammarTerm: "اسم اشارہ للبعيد", reveal: "You separated near from far with one precise Arabic word.", hookQuestion: "Why does Allah point to the Book with ذٰلِكَ?" },
      { title: "What Is This?", titleAr: "مَا هٰذَا؟", grammarTerm: "اسم استفهام", reveal: "You asked about things with مَا before learning the grammar name.", hookQuestion: "What question word opens the door to objects?" },
      { title: "Who Is This?", titleAr: "مَنْ هٰذَا؟", grammarTerm: "اسم استفهام للعاقل", reveal: "You learned that Arabic treats people differently from objects.", hookQuestion: "Why does a person need مَنْ instead of مَا?" },
    ],
  },
  {
    order: 2,
    sourceFile: "reader_lecture_02_nominal_sentence_prepositions.md",
    title: "Definite, Indefinite, and Place",
    titleAr: "نکرہ، معرفہ، أَيْنَ",
    description: "Tanween, alif-lam, nominal sentences, and simple prepositions.",
    hook: { ayahAr: "الْحَمْدُ لِلّٰهِ رَبِّ الْعَالَمِينَ", ayahRef: "Al-Fatiha 1:2", highlightedWord: "الْحَمْدُ" },
    examples: [
      card("بَيْتٌ", "a house", "baytun"),
      card("الْبَيْتُ", "the house", "al-baytu"),
      card("الْكِتَابُ جَدِيدٌ", "The book is new", "al-kitaabu jadeedun"),
      card("أَيْنَ الْقَلَمُ؟", "Where is the pen?", "ayna al-qalamu"),
    ],
    parseText: "الْكِتَابُ جَدِيدٌ",
    parseTokens: [token("الْكِتَابُ", "مبتدأ", "the book"), token("جَدِيدٌ", "خبر", "new")],
    conversation: ["أَيْنَ الْقَلَمُ؟", "الْقَلَمُ عَلَى الْمَكْتَبِ"],
    conversationDistractor: "مَنْ هٰذَا؟",
    distractor: "Who is this?",
    blankDistractor: "مَنْ",
    noorTip: "Al-Fatiha begins with a definite word; notice the ال in الْحَمْدُ.",
    noorTipUr: "الفاتحہ میں الْحَمْدُ کا ال غور سے دیکھیں۔",
    focuses: [
      { title: "A Word With Tanween", titleAr: "بَيْتٌ", grammarTerm: "نكرة", reveal: "Tanween quietly gave you 'a' without a separate Arabic word.", hookQuestion: "Where is the word 'a' hiding in بَيْتٌ?" },
      { title: "The Word With Al", titleAr: "الْبَيْتُ", grammarTerm: "معرفة", reveal: "You made a noun known by adding ال and removing tanween.", hookQuestion: "What changed when a house became the house?" },
      { title: "The Book Is New", titleAr: "الْكِتَابُ جَدِيدٌ", grammarTerm: "جملة اسمية", reveal: "You built a full sentence without a verb.", hookQuestion: "How does Arabic say 'is' without saying it?" },
      { title: "Where Is It?", titleAr: "أَيْنَ؟", grammarTerm: "ظرف ومكان", reveal: "You answered location questions with short place phrases.", hookQuestion: "What kind of answer does أَيْنَ expect?" },
    ],
  },
  {
    order: 3,
    sourceFile: "reader_lecture_03_mudaf_ilayh.md",
    title: "Possession and Calling",
    titleAr: "مضاف، مضاف إليه، يَا",
    description: "Idafa, ownership, vocative calling, and Hamzat ul-Wasl.",
    hook: { ayahAr: "بِسْمِ اللّٰهِ الرَّحْمٰنِ الرَّحِيمِ", ayahRef: "Al-Fatiha 1:1", highlightedWord: "بِسْمِ" },
    examples: [
      card("كِتَابُ مُحَمَّدٍ", "Muhammad's book", "kitaabu muhammadin"),
      card("بَيْتُ الطَّالِبِ", "the student's house", "baytu at-taalibi"),
      card("يَا مُحَمَّدُ", "O Muhammad", "yaa muhammadu"),
      card("بِسْمِ اللّٰهِ", "with the name of Allah", "bismillaah"),
    ],
    parseText: "كِتَابُ مُحَمَّدٍ",
    parseTokens: [token("كِتَابُ", "مضاف", "book"), token("مُحَمَّدٍ", "مضاف إليه", "Muhammad")],
    conversation: ["لِمَنْ هٰذَا الْكِتَابُ؟", "هٰذَا كِتَابُ مُحَمَّدٍ"],
    conversationDistractor: "أَيْنَ الْكِتَابُ؟",
    distractor: "This is far",
    blankDistractor: "فِي",
    noorTip: "Bismillah is an idafa phrase you have said since childhood.",
    noorTipUr: "بسم اللہ میں اضافت کو آج رات دوبارہ دیکھیں۔",
    focuses: [
      { title: "Muhammad's Book", titleAr: "كِتَابُ مُحَمَّدٍ", grammarTerm: "مركب إضافي", reveal: "You expressed ownership without an apostrophe or a word for 'of'.", hookQuestion: "Why does مُحَمَّدٍ end with kasra here?" },
      { title: "Whose Is This?", titleAr: "لِمَنْ هٰذَا؟", grammarTerm: "لام الملك", reveal: "You used لِ to ask and answer ownership.", hookQuestion: "What does لِ add to the question مَنْ?" },
      { title: "O Muhammad", titleAr: "يَا مُحَمَّدُ", grammarTerm: "حرف نداء", reveal: "You called someone directly and saw tanween disappear.", hookQuestion: "What changes when يَا enters before a name?" },
      { title: "Bismillah Connected", titleAr: "بِسْمِ اللّٰهِ", grammarTerm: "همزة الوصل", reveal: "You saw why اسم becomes بسم when connected.", hookQuestion: "Where did the hamza of اسم go?" },
    ],
  },
  {
    order: 4,
    sourceFile: "reader_lecture_04_murakkab_types_jumlah.md",
    title: "Compounds and Sentences",
    titleAr: "مرکب، جملہ، مذکر و مؤنث",
    description: "Types of compounds, nominal sentence structure, and gender agreement.",
    hook: { ayahAr: "وَالطُّورِ وَكِتَابٍ مَسْطُورٍ", ayahRef: "At-Tur 52:1-2", highlightedWord: "كِتَابٍ" },
    examples: [
      card("الْبَيْتُ كَبِيرٌ", "The house is big", "al-baytu kabeerun"),
      card("السَّيَّارَةُ جَدِيدَةٌ", "The car is new", "as-sayyaaratu jadeedatun"),
      card("كِتَابٌ مَفْتُوحٌ", "an open book", "kitaabun maftoohun"),
      card("غُرْفَةٌ صَغِيرَةٌ", "a small room", "ghurfatun sagheeratun"),
    ],
    parseText: "السَّيَّارَةُ جَدِيدَةٌ",
    parseTokens: [token("السَّيَّارَةُ", "مبتدأ", "the car"), token("جَدِيدَةٌ", "خبر", "new")],
    conversation: ["أَهٰذَا الْبَيْتُ كَبِيرٌ؟", "نَعَمْ، الْبَيْتُ كَبِيرٌ"],
    conversationDistractor: "هٰذَا كِتَابُ مُحَمَّدٍ",
    distractor: "Where is the pen?",
    blankDistractor: "ذٰلِكَ",
    noorTip: "Look for وصف patterns beside nouns when you recite short surahs.",
    noorTipUr: "قرآن میں اسم کے ساتھ صفت کو پہچاننے کی کوشش کریں۔",
    focuses: [
      { title: "Subject and News", titleAr: "مبتدأ وخبر", grammarTerm: "جملة اسمية", reveal: "You labelled the two halves of a sentence after using them naturally.", hookQuestion: "Which word is the thing, and which word gives the news?" },
      { title: "Describing a Noun", titleAr: "صفة وموصوف", grammarTerm: "مركب توصيفي", reveal: "You matched a noun with its description.", hookQuestion: "Why does the description follow the noun?" },
      { title: "Masculine Patterns", titleAr: "مذكر", grammarTerm: "مذكر", reveal: "You noticed masculine words often carry masculine descriptions.", hookQuestion: "What stays the same between كِتَابٌ and مَفْتُوحٌ?" },
      { title: "Feminine Patterns", titleAr: "مؤنث", grammarTerm: "مؤنث", reveal: "You saw feminine agreement through ة.", hookQuestion: "Why does جَدِيدَةٌ end with ة?" },
    ],
  },
  {
    order: 5,
    sourceFile: "reader_lecture_05_demonstratives_verb_intro.md",
    title: "More Demonstratives and First Verbs",
    titleAr: "أسماء الإشارة والفعل",
    description: "Complete pointing system, possession with ل, first verbs, and place adverbs.",
    hook: { ayahAr: "هٰذِهِ نَاقَةُ اللّٰهِ لَكُمْ آيَةً", ayahRef: "Al-A'raf 7:73", highlightedWord: "هٰذِهِ" },
    examples: [
      card("هٰذِهِ سَيَّارَةٌ", "This is a car", "haadhihi sayyaaratun"),
      card("تِلْكَ مَدْرَسَةٌ", "That is a school", "tilka madrasatun"),
      card("لِي كِتَابٌ", "I have a book", "lee kitaabun"),
      card("ذَهَبَ حَامِدٌ", "Hamid went", "dhahaba haamidun"),
    ],
    parseText: "ذَهَبَ حَامِدٌ",
    parseTokens: [token("ذَهَبَ", "فعل", "went"), token("حَامِدٌ", "فاعل", "Hamid")],
    conversation: ["لِمَنْ هٰذَا؟", "لِي هٰذَا الْكِتَابُ"],
    conversationDistractor: "مَا هٰذَا؟",
    distractor: "The house is large",
    blankDistractor: "مِنْ",
    noorTip: "The Quran uses هٰذِهِ for feminine nouns; watch how the pointing word changes.",
    noorTipUr: "هٰذِهِ اور هٰذَا کا فرق قرآن میں دیکھیں۔",
    focuses: [
      { title: "This Feminine", titleAr: "هٰذِهِ", grammarTerm: "اسم إشارة للمؤنث", reveal: "You pointed to feminine nouns with a new word.", hookQuestion: "Why is ناقة pointed to with هٰذِهِ?" },
      { title: "That Feminine", titleAr: "تِلْكَ", grammarTerm: "اسم إشارة للبعيد", reveal: "You completed the near/far pattern for feminine nouns.", hookQuestion: "What changes when the feminine thing is far?" },
      { title: "I Have", titleAr: "لِي", grammarTerm: "لام الملك", reveal: "You used a tiny particle to express possession.", hookQuestion: "How can لِ mean 'belongs to'?" },
      { title: "First Verb", titleAr: "ذَهَبَ", grammarTerm: "فعل ماض", reveal: "You met your first full past tense sentence.", hookQuestion: "Which word carries the action?" },
    ],
  },
  {
    order: 6,
    sourceFile: "reader_lecture_06_tawsifi_mawsool.md",
    title: "Description and Relative Clauses",
    titleAr: "مركب توصيفي والاسم الموصول",
    description: "Descriptive compounds, sentence analysis, and الذي.",
    hook: { ayahAr: "الَّذِي خَلَقَ فَسَوَّىٰ", ayahRef: "Al-A'la 87:2", highlightedWord: "الَّذِي" },
    examples: [
      card("الْوَلَدُ الَّذِي خَرَجَ", "the boy who left", "al-waladu alladhee kharaja"),
      card("الْبَيْتُ الْكَبِيرُ", "the big house", "al-baytu al-kabeeru"),
      card("رَجُلٌ صَالِحٌ", "a righteous man", "rajulun saalihun"),
      card("الْقَلَمُ الَّذِي عَلَى الْمَكْتَبِ", "the pen that is on the desk", "al-qalamu alladhee alal-maktabi"),
    ],
    parseText: "الْبَيْتُ الْكَبِيرُ",
    parseTokens: [token("الْبَيْتُ", "مبتدأ", "the house"), token("الْكَبِيرُ", "خبر", "big")],
    conversation: ["أَيْنَ الْقَلَمُ؟", "الْقَلَمُ الَّذِي عَلَى الْمَكْتَبِ"],
    conversationDistractor: "ذَهَبَ حَامِدٌ",
    distractor: "I have a book",
    blankDistractor: "تِلْكَ",
    noorTip: "Whenever you see الَّذِي, expect Arabic to attach more information to a noun.",
    noorTipUr: "الَّذِي کے بعد آنے والی وضاحت پر غور کریں۔",
    focuses: [
      { title: "The Big House", titleAr: "الْبَيْتُ الْكَبِيرُ", grammarTerm: "مركب توصيفي", reveal: "You made definite descriptions agree with definite nouns.", hookQuestion: "Why do both words carry ال?" },
      { title: "A Righteous Man", titleAr: "رَجُلٌ صَالِحٌ", grammarTerm: "صفة وموصوف", reveal: "You saw indefinite nouns described with indefinite descriptions.", hookQuestion: "Why do both words carry tanween?" },
      { title: "The One Who", titleAr: "الَّذِي", grammarTerm: "اسم موصول", reveal: "You attached a whole idea to one noun.", hookQuestion: "What does الَّذِي make you wait for?" },
      { title: "Longer Description", titleAr: "الَّذِي عَلَى الْمَكْتَبِ", grammarTerm: "صلة الموصول", reveal: "You completed a relative phrase with a place expression.", hookQuestion: "How does the sentence after الَّذِي complete the meaning?" },
    ],
  },
  {
    order: 7,
    sourceFile: "reader_lecture_07_attached_pronouns_munsar.md",
    title: "Attached Pronouns and Diptotes",
    titleAr: "ضمائر متصلة وممنوع من الصرف",
    description: "Attached pronouns, عند and مع, and first non-declining noun patterns.",
    hook: { ayahAr: "إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ", ayahRef: "Al-Fatiha 1:5", highlightedWord: "إِيَّاكَ" },
    examples: [
      card("كِتَابِي", "my book", "kitaabee"),
      card("كِتَابُكَ", "your book", "kitaabuka"),
      card("عِنْدِي قَلَمٌ", "I have a pen", "indee qalamun"),
      card("مَعِي أَخِي", "my brother is with me", "ma'ee akhee"),
    ],
    parseText: "عِنْدِي قَلَمٌ",
    parseTokens: [token("عِنْدِي", "خبر", "with me"), token("قَلَمٌ", "مبتدأ", "pen")],
    conversation: ["أَعِنْدَكَ قَلَمٌ؟", "نَعَمْ، عِنْدِي قَلَمٌ"],
    conversationDistractor: "هٰذِهِ سَيَّارَةٌ",
    distractor: "the boy who left",
    blankDistractor: "الَّذِي",
    noorTip: "Attached pronouns make Quranic address feel direct, especially in Al-Fatiha.",
    noorTipUr: "الفاتحہ میں إِيَّاكَ کے خطاب کو محسوس کریں۔",
    focuses: [
      { title: "My Book", titleAr: "كِتَابِي", grammarTerm: "ضمير متصل", reveal: "You attached ownership directly to the noun.", hookQuestion: "Where did the word 'my' go in كِتَابِي?" },
      { title: "Your Book", titleAr: "كِتَابُكَ", grammarTerm: "ضمير مخاطب", reveal: "You changed the attached ending to address someone.", hookQuestion: "How does كَ point to the listener?" },
      { title: "With Me", titleAr: "عِنْدِي", grammarTerm: "ظرف", reveal: "You used عند to express what someone has.", hookQuestion: "Why does عندي often translate as 'I have'?" },
      { title: "Together With", titleAr: "مَعِي", grammarTerm: "ظرف مع الضمير", reveal: "You attached a pronoun to مع and made a relationship phrase.", hookQuestion: "What does مع add that عند does not?" },
    ],
  },
  {
    order: 8,
    sourceFile: "reader_lecture_08_feminine_verb_allatee.md",
    title: "Feminine Verbs and Dialogue",
    titleAr: "الفعل المؤنث والتي",
    description: "Feminine verb forms, التي, family words, and conversation.",
    hook: { ayahAr: "الَّتِي لَمْ يُخْلَقْ مِثْلُهَا فِي الْبِلَادِ", ayahRef: "Al-Fajr 89:8", highlightedWord: "الَّتِي" },
    examples: [
      card("ذَهَبَتْ آمِنَةُ", "Aminah went", "dhahabat aaminatu"),
      card("رَجَعَتْ فَاطِمَةُ", "Fatimah returned", "raja'at faatimatu"),
      card("الْبِنْتُ الَّتِي خَرَجَتْ", "the girl who left", "al-bintu allatee kharajat"),
      card("أُمِّي فِي الْبَيْتِ", "my mother is in the house", "ummee fil-bayti"),
    ],
    parseText: "ذَهَبَتْ آمِنَةُ",
    parseTokens: [token("ذَهَبَتْ", "فعل", "went"), token("آمِنَةُ", "فاعل", "Aminah")],
    conversation: ["أَيْنَ أُمُّكَ؟", "أُمِّي فِي الْبَيْتِ"],
    conversationDistractor: "كِتَابُكَ جَدِيدٌ",
    distractor: "I have a pen",
    blankDistractor: "عِنْدِي",
    noorTip: "The Quran's feminine relative word الَّتِي opens a precise description.",
    noorTipUr: "الَّتِي کے بعد آنے والی صفت کو قرآن میں تلاش کریں۔",
    focuses: [
      { title: "She Went", titleAr: "ذَهَبَتْ", grammarTerm: "فعل ماض مؤنث", reveal: "You heard the feminine تْ at the end of the verb.", hookQuestion: "What tells you the doer is feminine?" },
      { title: "She Returned", titleAr: "رَجَعَتْ", grammarTerm: "علامة التأنيث", reveal: "You reused the same feminine sign with a new verb.", hookQuestion: "What stays stable between ذهبت and رجعت?" },
      { title: "The One Who Feminine", titleAr: "الَّتِي", grammarTerm: "اسم موصول مؤنث", reveal: "You matched the relative word to a feminine noun.", hookQuestion: "Why not use الَّذِي here?" },
      { title: "Family Dialogue", titleAr: "أُمِّي", grammarTerm: "ضمير متصل", reveal: "You used family words with attached pronouns in a real exchange.", hookQuestion: "Where is 'my' in أُمِّي?" },
    ],
  },
  {
    order: 9,
    sourceFile: "reader_lecture_09_jama_mukassar_salim.md",
    title: "Plural Nouns",
    titleAr: "جمع مكسر وجمع سالم",
    description: "Broken plurals, sound feminine plurals, and plural demonstratives.",
    hook: { ayahAr: "فِي قُلُوبِهِمْ مَرَضٌ", ayahRef: "Al-Baqarah 2:10", highlightedWord: "قُلُوبِهِمْ" },
    examples: [
      card("كِتَابٌ / كُتُبٌ", "book / books", "kitaabun / kutubun"),
      card("طَالِبَةٌ / طَالِبَاتٌ", "female student / female students", "taalibatun / taalibaatun"),
      card("هٰؤُلَاءِ طُلَّابٌ", "These are students", "haa'ulaa'i tullaabun"),
      card("أُولٰئِكَ رِجَالٌ", "Those are men", "ulaa'ika rijaalun"),
    ],
    parseText: "هٰؤُلَاءِ طُلَّابٌ",
    parseTokens: [token("هٰؤُلَاءِ", "مبتدأ", "these"), token("طُلَّابٌ", "خبر", "students")],
    conversation: ["مَنْ هٰؤُلَاءِ؟", "هٰؤُلَاءِ طُلَّابٌ"],
    conversationDistractor: "ذَهَبَتْ آمِنَةُ",
    distractor: "my mother is home",
    blankDistractor: "الَّتِي",
    noorTip: "Plural forms unlock many Quranic words, especially hearts, people, and believers.",
    noorTipUr: "قرآن میں جمع کے الفاظ جیسے قلوب اور رجال پر غور کریں۔",
    focuses: [
      { title: "Broken Plural", titleAr: "جمع مكسر", grammarTerm: "جمع مكسر", reveal: "You saw a plural whose inner shape changed.", hookQuestion: "Why does كِتَابٌ become كُتُبٌ instead of just adding an ending?" },
      { title: "Sound Feminine Plural", titleAr: "جمع مؤنث سالم", grammarTerm: "جمع مؤنث سالم", reveal: "You made a plural by adding ات.", hookQuestion: "What ending repeats in طَالِبَاتٌ?" },
      { title: "These People", titleAr: "هٰؤُلَاءِ", grammarTerm: "اسم إشارة للجمع", reveal: "You pointed to groups with a new demonstrative.", hookQuestion: "Why does هٰذَا no longer fit?" },
      { title: "Those People", titleAr: "أُولٰئِكَ", grammarTerm: "اسم إشارة للبعيد", reveal: "You completed plural pointing for distance.", hookQuestion: "How does Arabic point to a far group?" },
    ],
  },
  {
    order: 10,
    sourceFile: "reader_lecture_10_plural_pronouns_dialogue.md",
    title: "Plural Pronouns and Dialogue",
    titleAr: "ضمائر الجمع والحوار",
    description: "Plural pronouns, before and after, dialogue, and feminine plural verbs.",
    hook: { ayahAr: "أَنْعَمْتَ عَلَيْهِمْ", ayahRef: "Al-Fatiha 1:7", highlightedWord: "عَلَيْهِمْ" },
    examples: [
      card("هُمْ طُلَّابٌ", "They are students", "hum tullaabun"),
      card("هُنَّ طَالِبَاتٌ", "They are female students", "hunna taalibaatun"),
      card("قَبْلَ الصَّلَاةِ", "before prayer", "qabla as-salaati"),
      card("بَعْدَ الدَّرْسِ", "after the lesson", "ba'da ad-darsi"),
    ],
    parseText: "هُمْ طُلَّابٌ",
    parseTokens: [token("هُمْ", "مبتدأ", "they"), token("طُلَّابٌ", "خبر", "students")],
    conversation: ["مَتَى جَاءُوا؟", "جَاءُوا بَعْدَ الدَّرْسِ"],
    conversationDistractor: "هٰذَا بَيْتٌ",
    distractor: "This is a car",
    blankDistractor: "ذٰلِكَ",
    noorTip: "Al-Fatiha uses عليهم; notice how the pronoun is attached to a preposition.",
    noorTipUr: "الفاتحہ میں عَلَيْهِمْ کو پہچانیں۔",
    focuses: [
      { title: "They Masculine", titleAr: "هُمْ", grammarTerm: "ضمير جمع مذكر", reveal: "You used a plural pronoun for a group.", hookQuestion: "What does هُمْ gather together?" },
      { title: "They Feminine", titleAr: "هُنَّ", grammarTerm: "ضمير جمع مؤنث", reveal: "You separated feminine groups from masculine groups.", hookQuestion: "Why does Arabic need a different they?" },
      { title: "Before", titleAr: "قَبْلَ", grammarTerm: "ظرف زمان", reveal: "You placed an action before another moment.", hookQuestion: "What does قبل make you expect after it?" },
      { title: "After", titleAr: "بَعْدَ", grammarTerm: "ظرف زمان", reveal: "You placed an action after another moment.", hookQuestion: "How does بعد organize time?" },
    ],
  },
  {
    order: 11,
    sourceFile: "reader_lecture_11_numbers_tathnia.md",
    title: "Numbers and Dual",
    titleAr: "الأعداد والتثنية",
    description: "Numbers 3-10, tamyeez, dual forms, and kam.",
    hook: { ayahAr: "سَبْعَ سَمَاوَاتٍ", ayahRef: "Al-Mulk 67:3", highlightedWord: "سَبْعَ" },
    examples: [
      card("ثَلَاثَةُ كُتُبٍ", "three books", "thalaathatu kutubin"),
      card("خَمْسُ طَالِبَاتٍ", "five female students", "khamsu taalibaatin"),
      card("كِتَابَانِ", "two books", "kitaabaani"),
      card("كَمْ قَلَمًا عِنْدَكَ؟", "How many pens do you have?", "kam qalaman indaka"),
    ],
    parseText: "ثَلَاثَةُ كُتُبٍ",
    parseTokens: [token("ثَلَاثَةُ", "مبتدأ", "three"), token("كُتُبٍ", "مضاف إليه", "books")],
    conversation: ["كَمْ قَلَمًا عِنْدَكَ؟", "عِنْدِي ثَلَاثَةُ أَقْلَامٍ"],
    conversationDistractor: "هُمْ طُلَّابٌ",
    distractor: "after the lesson",
    blankDistractor: "بَعْدَ",
    noorTip: "Numbers in the Quran often carry grammar after them; سَبْعَ سَمَاوَاتٍ is a perfect doorway.",
    noorTipUr: "سَبْعَ سَمَاوَاتٍ میں عدد اور معدود دیکھیں۔",
    focuses: [
      { title: "Three to Ten", titleAr: "ثلاثة إلى عشرة", grammarTerm: "عدد", reveal: "You counted groups with Arabic number patterns.", hookQuestion: "Why does the counted noun change after the number?" },
      { title: "The Counted Thing", titleAr: "تمييز", grammarTerm: "تمييز", reveal: "You saw the noun after a number explain what is counted.", hookQuestion: "What does كُتُبٍ clarify?" },
      { title: "Two Things", titleAr: "تثنية", grammarTerm: "مثنى", reveal: "You made two without using a separate word for two.", hookQuestion: "What does انِ add to كتاب?" },
      { title: "How Many?", titleAr: "كَمْ", grammarTerm: "اسم استفهام للعدد", reveal: "You asked for number with one compact question word.", hookQuestion: "What kind of answer does كَمْ demand?" },
    ],
  },
  {
    order: 12,
    sourceFile: "reader_lecture_12_colors_ghayr_munsarif.md",
    title: "Colors and Diptotes",
    titleAr: "الألوان والممنوع من الصرف",
    description: "Color patterns, diptote categories, and non-rational plural agreement.",
    hook: { ayahAr: "صُفْرٌ فَاقِعٌ لَوْنُهَا", ayahRef: "Al-Baqarah 2:69", highlightedWord: "صُفْرٌ" },
    examples: [
      card("أَحْمَرُ", "red", "ahmaru"),
      card("بَيْضَاءُ", "white", "baydaa'u"),
      card("مَسَاجِدُ كَبِيرَةٌ", "large mosques", "masaajidu kabeeratun"),
      card("فِي مَكَّةَ", "in Makkah", "fee makkata"),
    ],
    parseText: "فِي مَكَّةَ",
    parseTokens: [token("فِي", "حرف جر", "in"), token("مَكَّةَ", "مضاف إليه", "Makkah")],
    conversation: ["مَا لَوْنُ الْكِتَابِ؟", "لَوْنُهُ أَحْمَرُ"],
    conversationDistractor: "كِتَابَانِ",
    distractor: "how many pens",
    blankDistractor: "كَمْ",
    noorTip: "Color words in Quranic descriptions often carry special shapes.",
    noorTipUr: "قرآن میں رنگوں کے الفاظ کی بناوٹ پر غور کریں۔",
    focuses: [
      { title: "Color Pattern", titleAr: "أَفْعَل", grammarTerm: "اسم لون", reveal: "You recognized the common masculine color shape.", hookQuestion: "What pattern do أَحْمَرُ and أَسْوَدُ share?" },
      { title: "Feminine Color", titleAr: "فَعْلَاء", grammarTerm: "مؤنث اللون", reveal: "You matched color to feminine form.", hookQuestion: "Why does white become بَيْضَاءُ?" },
      { title: "Diptote Place", titleAr: "مكة", grammarTerm: "ممنوع من الصرف", reveal: "You saw a noun take fatḥa where you expected kasra.", hookQuestion: "Why is مَكَّةَ special after في?" },
      { title: "Non-Rational Plural", titleAr: "جمع غير عاقل", grammarTerm: "جمع غير عاقل", reveal: "You treated non-human plurals like feminine singular in description.", hookQuestion: "Why is مَسَاجِدُ described with كَبِيرَةٌ?" },
    ],
  },
  {
    order: 13,
    sourceFile: "reader_lecture_13_ghayr_munsarif_inna_zu.md",
    title: "Inna, Diptotes, and Possessors",
    titleAr: "إنّ، ذو، ممنوع من الصرف",
    description: "Ghayr munsarif in jar, inna and sisters, laalla, zu, and prices.",
    hook: { ayahAr: "إِنَّ اللّٰهَ غَفُورٌ رَحِيمٌ", ayahRef: "Al-Baqarah 2:173", highlightedWord: "إِنَّ" },
    examples: [
      card("إِنَّ اللّٰهَ رَحِيمٌ", "Indeed Allah is merciful", "inna allaaha raheemun"),
      card("لَعَلَّكَ تَفْهَمُ", "Perhaps you understand", "la'allaka tafhamu"),
      card("ذُو عِلْمٍ", "possessor of knowledge", "dhoo ilmin"),
      card("السِّعْرُ عَشَرَةُ رِيَالَاتٍ", "The price is ten riyals", "as-si'ru asharatu riyaalaatin"),
    ],
    parseText: "إِنَّ اللّٰهَ رَحِيمٌ",
    parseTokens: [token("إِنَّ", "حرف جر", "indeed"), token("اللّٰهَ", "مفعول", "Allah"), token("رَحِيمٌ", "خبر", "merciful")],
    conversation: ["كَمِ السِّعْرُ؟", "السِّعْرُ عَشَرَةُ رِيَالَاتٍ"],
    conversationDistractor: "لَوْنُهُ أَحْمَرُ",
    distractor: "in Makkah",
    blankDistractor: "فِي",
    noorTip: "إِنَّ appears constantly in the Quran to add certainty and emphasis.",
    noorTipUr: "إِنَّ کے بعد اسم کے اعراب کو قرآن میں دیکھیں۔",
    focuses: [
      { title: "Indeed", titleAr: "إِنَّ", grammarTerm: "حرف مشبه بالفعل", reveal: "You felt emphasis before naming the particle.", hookQuestion: "What force does إِنَّ add to a sentence?" },
      { title: "Perhaps", titleAr: "لَعَلَّ", grammarTerm: "أخوات إن", reveal: "You met another particle that changes the noun after it.", hookQuestion: "How does لعل change the mood of a sentence?" },
      { title: "Possessor", titleAr: "ذُو", grammarTerm: "الأسماء الخمسة", reveal: "You expressed possession as a quality.", hookQuestion: "What does ذو make someone carry?" },
      { title: "Prices", titleAr: "السعر", grammarTerm: "تمييز العدد", reveal: "You used numbers in a market-style sentence.", hookQuestion: "What does the counted money clarify?" },
    ],
  },
  {
    order: 14,
    sourceFile: "reader_lecture_14_laysa_inna_tafdheel.md",
    title: "Laysa, Inna, and Comparison",
    titleAr: "ليس، إنّ، اسم التفضيل",
    description: "Negation with laysa, deferred subjects after inna, comparison, and numbers 11-19.",
    hook: { ayahAr: "لَيْسَ كَمِثْلِهِ شَيْءٌ", ayahRef: "Ash-Shura 42:11", highlightedWord: "لَيْسَ" },
    examples: [
      card("لَيْسَ الْبَيْتُ كَبِيرًا", "The house is not big", "laysa al-baytu kabeeran"),
      card("إِنَّ فِي ذٰلِكَ آيَةً", "Indeed in that is a sign", "inna fee dhaalika aayatan"),
      card("هٰذَا أَكْبَرُ مِنْ ذٰلِكَ", "This is bigger than that", "haadha akbaru min dhaalika"),
      card("أَحَدَ عَشَرَ كِتَابًا", "eleven books", "ahada ashara kitaaban"),
    ],
    parseText: "لَيْسَ الْبَيْتُ كَبِيرًا",
    parseTokens: [token("لَيْسَ", "فعل", "is not"), token("الْبَيْتُ", "فاعل", "house"), token("كَبِيرًا", "خبر", "big")],
    conversation: ["أَهٰذَا أَكْبَرُ؟", "نَعَمْ، هٰذَا أَكْبَرُ مِنْ ذٰلِكَ"],
    conversationDistractor: "ذُو عِلْمٍ",
    distractor: "The price is ten riyals",
    blankDistractor: "ذُو",
    noorTip: "لَيْسَ كَمِثْلِهِ شَيْءٌ is a powerful ayah for negation and uniqueness.",
    noorTipUr: "لَيْسَ والی آیت میں نفی کا انداز دیکھیں۔",
    focuses: [
      { title: "It Is Not", titleAr: "لَيْسَ", grammarTerm: "فعل ناقص", reveal: "You negated a nominal sentence with one verb-like word.", hookQuestion: "What does لَيْسَ do to the sentence?" },
      { title: "In That Is a Sign", titleAr: "إِنَّ فِي ذٰلِكَ", grammarTerm: "خبر مقدم", reveal: "You saw the خبر come before the اسم.", hookQuestion: "Why does Arabic sometimes delay the subject?" },
      { title: "Bigger Than", titleAr: "أَكْبَرُ مِنْ", grammarTerm: "اسم تفضيل", reveal: "You compared two things with the أفعل pattern.", hookQuestion: "What does مِنْ mean after أَكْبَرُ?" },
      { title: "Eleven to Nineteen", titleAr: "أحد عشر", grammarTerm: "عدد مركب", reveal: "You met compound numbers with a singular counted noun.", hookQuestion: "Why does كِتَابًا stay singular after eleven?" },
    ],
  },
  {
    order: 15,
    sourceFile: "reader_lecture_15_ism_tafdeel_numbers_past_tense.md",
    title: "Comparison, Numbers, and Past Tense",
    titleAr: "اسم التفضيل، الأعداد، الفعل الماضي",
    description: "Comparative and superlative, numbers 11-20, ordinals, لكن and كأن, and past tense verbs.",
    hook: { ayahAr: "وَالْآخِرَةُ خَيْرٌ وَأَبْقَىٰ", ayahRef: "Al-A'la 87:17", highlightedWord: "خَيْرٌ" },
    examples: [
      card("هٰذَا أَحْسَنُ بَيْتٍ", "This is the best house", "haadha ahsanu baytin"),
      card("فِي السَّنَةِ اثْنَا عَشَرَ شَهْرًا", "In the year are twelve months", "fis-sanati ithnaa ashara shahran"),
      card("الدَّرْسُ الأَوَّلُ", "the first lesson", "ad-darsu al-awwalu"),
      card("ذَهَبُوا إِلَى الْجَامِعَةِ", "They went to the university", "dhahaboo ilal-jaami'ati"),
    ],
    parseText: "ذَهَبُوا إِلَى الْجَامِعَةِ",
    parseTokens: [token("ذَهَبُوا", "فعل", "they went"), token("إِلَى", "حرف جر", "to"), token("الْجَامِعَةِ", "مضاف إليه", "university")],
    conversation: ["مَتَى ذَهَبُوا؟", "ذَهَبُوا إِلَى الْجَامِعَةِ بَعْدَ الدَّرْسِ"],
    conversationDistractor: "لَيْسَ الْبَيْتُ كَبِيرًا",
    distractor: "eleven books",
    blankDistractor: "لَيْسَ",
    noorTip: "خَيْرٌ in Al-A'la is a Quranic comparison: the Hereafter is better and lasting.",
    noorTipUr: "والآخرة خير وأبقى میں تقابل کو سمجھ کر پڑھیں۔",
    focuses: [
      { title: "Best House", titleAr: "أَحْسَنُ بَيْتٍ", grammarTerm: "اسم تفضيل", reveal: "You moved from bigger than to best of a group.", hookQuestion: "How does أَحْسَنُ become 'best' here?" },
      { title: "Twelve Months", titleAr: "اثنا عشر", grammarTerm: "عدد مركب", reveal: "You saw how twelve behaves differently from nearby numbers.", hookQuestion: "What makes اثنا عشر special?" },
      { title: "First Lesson", titleAr: "الدَّرْسُ الأَوَّلُ", grammarTerm: "عدد ترتيبي", reveal: "You used a number as a description.", hookQuestion: "Why does الأَوَّلُ follow الدرس like a صفة?" },
      { title: "They Went", titleAr: "ذَهَبُوا", grammarTerm: "فعل ماض للجمع", reveal: "You read a past tense verb with a plural doer built into it.", hookQuestion: "What does وا at the end of ذهبوا tell you?" },
    ],
  },
];

const chapters = specs.map(chapter);

module.exports = {
  chapters,
  specs,
};
