const DEFAULT_FLASHCARD_TIP_EN =
  "Read the Arabic aloud before you flip the card. Slow, accurate repetition is better than rushing.";
const DEFAULT_FLASHCARD_TIP_UR =
  "جواب دیکھنے سے پہلے عربی کو آواز کے ساتھ پڑھیں۔ آہستہ اور درست دہرانا جلدی کرنے سے بہتر ہے۔";
const DEFAULT_QUIZ_TIP_EN =
  "Eliminate one wrong option first, then compare the remaining choices carefully.";
const DEFAULT_QUIZ_TIP_UR =
  "پہلے ایک غلط جواب نکالیں، پھر باقی اختیارات کو غور سے دیکھیں۔";

function word(arabic, transliteration, meaningEn, meaningUr) {
  return {
    arabic,
    transliteration,
    meaning_en: meaningEn,
    meaning_ur: meaningUr,
  };
}

function flashcardLesson({
  title,
  titleAr,
  prompt,
  answer,
  focus,
  hook,
  explanationEn,
  explanationUr,
  quranicExample,
  conversationExample,
  reviewWords = [],
  tipEn = DEFAULT_FLASHCARD_TIP_EN,
  tipUr = DEFAULT_FLASHCARD_TIP_UR,
}) {
  return {
    title,
    titleAr,
    type: "FLASHCARD",
    xpReward: 10,
    content: {
      question: prompt ?? focus?.arabic ?? title,
      answer,
      arabic: focus?.arabic,
      transliteration: focus?.transliteration,
      meaning_en: focus?.meaning_en,
      meaning_ur: focus?.meaning_ur,
      hook,
      explanation_en: explanationEn,
      explanation_ur: explanationUr,
      quranic_example: quranicExample,
      conversation_example: conversationExample,
      ustadh_noor_tip_en: tipEn,
      ustadh_noor_tip_ur: tipUr,
      review_words: reviewWords.filter(Boolean),
      example: quranicExample ? `${quranicExample.arabic} — ${quranicExample.meaning_en}` : undefined,
    },
  };
}

function quizLesson({
  title,
  titleAr,
  type = "FILL_BLANK",
  question,
  questionUr,
  answer,
  options,
  hook,
  focus,
  explanationEn,
  explanationUr,
  quranicExample,
  conversationExample,
  reviewWords = [],
  tipEn = DEFAULT_QUIZ_TIP_EN,
  tipUr = DEFAULT_QUIZ_TIP_UR,
}) {
  return {
    title,
    titleAr,
    type,
    xpReward: 10,
    content: {
      question,
      question_ur: questionUr,
      answer,
      options,
      arabic: focus?.arabic,
      transliteration: focus?.transliteration,
      meaning_en: focus?.meaning_en,
      meaning_ur: focus?.meaning_ur,
      hook,
      explanation_en: explanationEn,
      explanation_ur: explanationUr,
      quranic_example: quranicExample,
      conversation_example: conversationExample,
      ustadh_noor_tip_en: tipEn,
      ustadh_noor_tip_ur: tipUr,
      review_words: reviewWords.filter(Boolean),
    },
  };
}

function chapter(order, title, titleAr, description, worldMapX, worldMapY, lessons) {
  return {
    order,
    title,
    titleAr,
    description,
    worldMapX,
    worldMapY,
    isLocked: order !== 1,
    lessons,
  };
}

const chapters = [
  chapter(
    1,
    "The Arabic Alphabet: Part 1",
    "الأبجدية العربية ١",
    "Makkah · Learn the first connected letter families from alif to kha with sound, shape, and recognition practice.",
    0.12,
    0.12,
    [
      flashcardLesson({
        title: "Alif",
        titleAr: "الألف",
        prompt: "ا",
        answer: "Alif - often carries a long aa sound.",
        focus: word("ا", "Alif", "The mother letter of the Arabic script.", "عربی رسم الخط کا بنیادی حرف۔"),
        hook: word("اقْرَأْ", "Iqra'", "Read", "پڑھ"),
        explanationEn: "Meet Alif: learn its shape, name, and calm upright sound. It anchors many Quranic and daily Arabic words.",
        explanationUr: "الف سے واقف ہوں۔ اس کی شکل، نام، اور سیدھی آواز یاد کریں۔ یہ قرآن اور روزمرہ عربی کے بہت سے الفاظ میں آتا ہے۔",
        quranicExample: word("اللّٰه", "Allah", "Allah", "اللہ"),
        conversationExample: word("أَنا", "ana", "I", "میں"),
        reviewWords: [word("أَسَد", "asad", "lion", "شیر")],
      }),
      flashcardLesson({
        title: "Ba & Ta",
        titleAr: "الباء والتاء",
        prompt: "ب ت",
        answer: "Ba and Ta share the same base shape; the dots change the sound.",
        focus: word("ب ت", "ba, ta", "Two dotted sister letters.", "دو نقطوں والے بہن بھائی حروف۔"),
        hook: word("بِسْمِ", "bismi", "in the name of", "نام سے"),
        explanationEn: "Ba and Ta look alike until the dots guide you. Train your eye to notice where the dots sit before you pronounce the letter.",
        explanationUr: "باء اور تاء ایک ہی شکل رکھتے ہیں، فرق صرف نقطوں کا ہے۔ آواز نکالنے سے پہلے نقطوں کی جگہ کو غور سے دیکھیں۔",
        quranicExample: word("بِسْمِ اللّٰهِ", "Bismillah", "In the name of Allah", "اللہ کے نام سے"),
        conversationExample: word("بَيْت", "bayt", "house", "گھر"),
        reviewWords: [word("ب", "ba", "B sound", "ب کی آواز"), word("ت", "ta", "T sound", "ت کی آواز")],
      }),
      flashcardLesson({
        title: "Tha & Jim",
        titleAr: "الثاء والجيم",
        prompt: "ث ج",
        answer: "Tha uses three dots above; Jim carries one dot below.",
        focus: word("ث ج", "tha, jim", "Two letters with very different dot positions.", "دو حروف جن کے نقطے مختلف جگہ پر ہوتے ہیں۔"),
        hook: word("ثَوَاب", "thawab", "reward", "ثواب"),
        explanationEn: "This pair teaches visual discipline. Tha and Jim belong to different shape families, so dots and curve direction both matter.",
        explanationUr: "یہ سبق نظر کی باریکی سکھاتا ہے۔ ثاء اور جیم کی شکلیں بھی مختلف ہیں اور نقطوں کی جگہ بھی، اس لیے دونوں چیزیں یاد رکھیں۔",
        quranicExample: word("جَنَّة", "jannah", "garden / Paradise", "جنت"),
        conversationExample: word("ثَوْب", "thawb", "garment", "لباس"),
        reviewWords: [word("ج", "jim", "J sound", "ج کی آواز")],
      }),
      flashcardLesson({
        title: "Ha & Kha",
        titleAr: "الحاء والخاء",
        prompt: "ح خ",
        answer: "Ha is a soft throat letter; Kha adds a rough, breathy sound.",
        focus: word("ح خ", "ha, kha", "Two deep throat letters.", "گلے سے نکلنے والے دو حروف۔"),
        hook: word("الحَمْدُ", "al-hamdu", "all praise", "سب تعریف"),
        explanationEn: "Ha and Kha both come from the throat. Ha stays soft and airy, while Kha adds a scratchy breath from deeper in the throat.",
        explanationUr: "حاء اور خاء دونوں گلے سے نکلتے ہیں۔ حاء نرم ہے جبکہ خاء میں زیادہ کھردری سانس شامل ہوتی ہے۔",
        quranicExample: word("خَلَقَ", "khalaqa", "He created", "اس نے پیدا کیا"),
        conversationExample: word("خُبْز", "khubz", "bread", "روٹی"),
        reviewWords: [word("ح", "ha", "soft h", "نرم ہ"), word("خ", "kha", "kh sound", "خ کی آواز")],
      }),
      flashcardLesson({
        title: "Dal & Dhal",
        titleAr: "الدال والذال",
        prompt: "د ذ",
        answer: "Dal and Dhal do not connect forward to the next letter.",
        focus: word("د ذ", "dal, dhal", "One-way connector letters.", "ایسے حروف جو آگے والے حرف سے نہیں جڑتے۔"),
        hook: word("ذِكْر", "dhikr", "remembrance", "ذکر"),
        explanationEn: "These letters teach an important joining rule: Dal and Dhal can join the letter before them, but not the one after.",
        explanationUr: "یہ دونوں حروف جوڑنے کا اہم اصول سکھاتے ہیں۔ دال اور ذال پچھلے حرف سے جڑتے ہیں مگر اگلے سے نہیں۔",
        quranicExample: word("ذٰلِكَ", "dhalika", "that", "وہ"),
        conversationExample: word("دار", "dar", "home", "گھر"),
        reviewWords: [word("د", "dal", "D sound", "د کی آواز"), word("ذ", "dhal", "th in 'this'", "ذ کی آواز")],
      }),
      flashcardLesson({
        title: "Ra & Zay",
        titleAr: "الراء والزاي",
        prompt: "ر ز",
        answer: "Ra rolls lightly; Zay keeps the same shape with a dot above.",
        focus: word("ر ز", "ra, zay", "A rolling letter pair.", "لڑھکنے والی آواز والا جوڑا۔"),
        hook: word("رَحْمَة", "rahmah", "mercy", "رحمت"),
        explanationEn: "Ra and Zay are another visual pair. Practice the tongue movement for Ra, then notice how one extra dot turns it into Zay.",
        explanationUr: "راء اور زاء ایک اور شکل والے جوڑے ہیں۔ راء کی زبان کی حرکت الگ سے مشق کریں، پھر ایک نقطہ اسے زاء بناتا ہے۔",
        quranicExample: word("رَبّ", "rabb", "Lord", "رب"),
        conversationExample: word("زَيْت", "zayt", "oil", "تیل"),
        reviewWords: [word("ر", "ra", "R sound", "ر کی آواز"), word("ز", "zay", "Z sound", "ز کی آواز")],
      }),
      quizLesson({
        title: "Review: Alif to Kha",
        titleAr: "مراجعة ا إلى خ",
        type: "FILL_BLANK",
        question: "Which letter below is Kha?",
        questionUr: "نیچے دیے گئے اختیارات میں خاء کون سا ہے؟",
        answer: "خ",
        options: ["ح", "خ", "ج", "ذ"],
        hook: word("اقْرَأْ بِاسْمِ رَبِّكَ", "Iqra' bismi rabbika", "Read in the name of your Lord", "اپنے رب کے نام سے پڑھو"),
        focus: word("ا-خ", "alif to kha", "The first sound family review.", "پہلے حروف کی مجموعی دہرائی۔"),
        explanationEn: "This review checks whether you can separate similar-looking letters by shape and dots.",
        explanationUr: "یہ دہرائی دیکھتی ہے کہ آپ شکل اور نقطوں کی مدد سے ملتے جلتے حروف کو الگ پہچان سکتے ہیں یا نہیں۔",
        quranicExample: word("خَلَقَ", "khalaqa", "He created", "اس نے پیدا کیا"),
        conversationExample: word("بَيْت", "bayt", "house", "گھر"),
        reviewWords: [word("ا", "alif", "alif", "الف"), word("ب", "ba", "ba", "باء"), word("خ", "kha", "kha", "خاء")],
      }),
    ]
  ),
  chapter(
    2,
    "The Arabic Alphabet: Part 2",
    "الأبجدية العربية ٢",
    "Makkah · Continue through the middle of the alphabet and get used to emphatic and throat sounds.",
    0.18,
    0.18,
    [
      flashcardLesson({
        title: "Sin & Shin",
        titleAr: "السين والشين",
        prompt: "س ش",
        answer: "Shin is Sin with three dots above.",
        focus: word("س ش", "sin, shin", "Two tooth-shaped letters.", "دانتوں جیسی شکل والے دو حروف۔"),
        hook: word("شَمْس", "shams", "sun", "سورج"),
        explanationEn: "Both letters have three teeth in their shape. Sin stays plain, while Shin adds three dots and shifts to the sh sound.",
        explanationUr: "ان دونوں حروف کی شکل میں تین دانت ہوتے ہیں۔ سین سادہ رہتا ہے جبکہ شین تین نقطوں سے sh کی آواز دیتا ہے۔",
        quranicExample: word("سَمَاء", "sama'", "sky", "آسمان"),
        conversationExample: word("شاي", "shay", "tea", "چائے"),
        reviewWords: [word("س", "sin", "s sound", "س کی آواز"), word("ش", "shin", "sh sound", "ش کی آواز")],
      }),
      flashcardLesson({
        title: "Sad & Dad",
        titleAr: "الصاد والضاد",
        prompt: "ص ض",
        answer: "Sad and Dad are heavy emphatic letters; Dad adds a dot.",
        focus: word("ص ض", "sad, dad", "Heavy sister letters.", "بھاری آواز والے دو حروف۔"),
        hook: word("صِرَاط", "sirat", "path", "راستہ"),
        explanationEn: "These letters sound heavier than Sin and Dal. Keep the tongue broad and the mouth fuller when you pronounce them.",
        explanationUr: "یہ حروف سین اور دال سے زیادہ بھاری ہیں۔ انہیں پڑھتے وقت زبان کو پھیلا کر اور منہ کو بھر کر آواز نکالیں۔",
        quranicExample: word("صِرَاطَ الْمُسْتَقِيم", "sirat al-mustaqim", "the straight path", "سیدھا راستہ"),
        conversationExample: word("ضَيْف", "dayf", "guest", "مہمان"),
        reviewWords: [word("ص", "sad", "heavy s", "بھاری ص"), word("ض", "dad", "heavy d", "بھاری ض")],
      }),
      flashcardLesson({
        title: "Ta & Dha",
        titleAr: "الطاء والظاء",
        prompt: "ط ظ",
        answer: "Ta and Dha are emphatic letters; Dha adds a dot and a voiced sound.",
        focus: word("ط ظ", "ta, dha", "Another emphatic pair.", "بھاری حروف کا ایک اور جوڑا۔"),
        hook: word("ظُلُمَات", "zulumat", "darknesses", "تاریکیاں"),
        explanationEn: "These letters push the sound upward in the mouth. Listen for the firmness in Ta and the voiced quality in Dha.",
        explanationUr: "ان حروف کی آواز منہ کے اوپر والے حصے میں بھر جاتی ہے۔ طاء کی مضبوطی اور ظاء کی بھاری آواز پر توجہ دیں۔",
        quranicExample: word("طَيِّب", "tayyib", "good / pure", "پاک"),
        conversationExample: word("ظَهْر", "zuhr", "back / noon prayer", "ظہر"),
        reviewWords: [word("ط", "ta", "heavy t", "بھاری ط"), word("ظ", "dha", "heavy z/th", "بھاری ظ")],
      }),
      flashcardLesson({
        title: "Ain & Ghain",
        titleAr: "العين والغين",
        prompt: "ع غ",
        answer: "Ain is deep and squeezed; Ghain adds a rough voiced sound.",
        focus: word("ع غ", "ayn, ghayn", "Uniquely Arabic throat letters.", "عربی کے خاص گلے والے حروف۔"),
        hook: word("العَالَمِين", "al-'alamin", "the worlds", "تمام جہان"),
        explanationEn: "Ain and Ghain take patience. Aim for the deep throat position first, then add voicing and roughness for Ghain.",
        explanationUr: "عین اور غین کو وقت دے کر سیکھیں۔ پہلے گلے کی گہری جگہ پکڑیں، پھر غین میں آواز اور کھردرا پن شامل کریں۔",
        quranicExample: word("غَفُور", "ghafur", "Most Forgiving", "بہت بخشنے والا"),
        conversationExample: word("عِلْم", "'ilm", "knowledge", "علم"),
        reviewWords: [word("ع", "'ayn", "ayn sound", "عین کی آواز"), word("غ", "ghayn", "gh sound", "غین کی آواز")],
      }),
      flashcardLesson({
        title: "Fa & Qaf",
        titleAr: "الفاء والقاف",
        prompt: "ف ق",
        answer: "Fa takes one dot above; Qaf takes two and comes from deeper in the mouth.",
        focus: word("ف ق", "fa, qaf", "A light pair with a deep contrast.", "ہونٹ اور حلق کے فرق والا جوڑا۔"),
        hook: word("قُرْآن", "Qur'an", "Quran", "قرآن"),
        explanationEn: "Fa is produced with the lips and teeth, while Qaf comes from the back of the tongue. Their dots help your eye remember the sound change.",
        explanationUr: "فاء ہونٹ اور دانت سے نکلتی ہے جبکہ قاف زبان کے پچھلے حصے سے نکلتی ہے۔ نقطے آپ کو آواز کا فرق یاد رکھنے میں مدد دیتے ہیں۔",
        quranicExample: word("فَلَق", "falaq", "daybreak", "صبح"),
        conversationExample: word("قَلَم", "qalam", "pen", "قلم"),
        reviewWords: [word("ف", "fa", "f sound", "ف کی آواز"), word("ق", "qaf", "q sound", "ق کی آواز")],
      }),
      flashcardLesson({
        title: "Kaf & Lam",
        titleAr: "الكاف واللام",
        prompt: "ك ل",
        answer: "Kaf and Lam are common, easy connectors in Arabic words.",
        focus: word("ك ل", "kaf, lam", "Two high-frequency letters.", "دو بہت کثرت سے آنے والے حروف۔"),
        hook: word("لَكَ", "laka", "for you", "تمہارے لیے"),
        explanationEn: "You will see Kaf and Lam everywhere. Practice how easily they connect into words and how Lam often begins common Quranic phrases.",
        explanationUr: "کاف اور لام ہر جگہ نظر آتے ہیں۔ ان کا الفاظ میں آسانی سے جڑنا یاد کریں، خاص طور پر لام قرآن میں بہت آتا ہے۔",
        quranicExample: word("كِتَاب", "kitab", "book", "کتاب"),
        conversationExample: word("لَبَن", "laban", "milk / yogurt drink", "دودھ"),
        reviewWords: [word("ك", "kaf", "k sound", "ک کی آواز"), word("ل", "lam", "l sound", "ل کی آواز")],
      }),
      quizLesson({
        title: "Review: Sin to Dad",
        titleAr: "مراجعة س إلى ض",
        type: "FILL_BLANK",
        question: "Which letter below is Ghain?",
        questionUr: "نیچے دیے گئے اختیارات میں غین کون سا ہے؟",
        answer: "غ",
        options: ["ع", "غ", "ف", "ق"],
        hook: word("غَفُورٌ رَحِيمٌ", "ghafurun rahim", "Forgiving, Merciful", "بخشنے والا، رحم کرنے والا"),
        focus: word("س-ض", "sin to dad", "The second alphabet review.", "دوسرے حصے کی حروفی دہرائی۔"),
        explanationEn: "This review asks you to separate emphatic, dotted, and throat letters accurately.",
        explanationUr: "یہ دہرائی آپ سے چاہتی ہے کہ آپ بھاری، نقطوں والے، اور گلے سے نکلنے والے حروف کو درست پہچانیں۔",
        quranicExample: word("قُرْآن", "Qur'an", "Quran", "قرآن"),
        conversationExample: word("شاي", "shay", "tea", "چائے"),
        reviewWords: [word("ش", "shin", "shin", "شین"), word("ص", "sad", "sad", "صاد"), word("ق", "qaf", "qaf", "قاف")],
      }),
    ]
  ),
  chapter(
    3,
    "The Arabic Alphabet: Part 3 + Special Letters",
    "الأبجدية العربية ٣",
    "Makkah · Finish the alphabet, then learn Hamza, Lam-Alif, and the sun/moon letter rule.",
    0.24,
    0.22,
    [
      flashcardLesson({
        title: "Mim & Nun",
        titleAr: "الميم والنون",
        prompt: "م ن",
        answer: "Mim and Nun are nasal letters used in very common Arabic words.",
        focus: word("م ن", "mim, nun", "Two nasal letters that appear constantly.", "ناک سے نکلنے والی دو عام آوازیں۔"),
        hook: word("مِنْ", "min", "from", "سے"),
        explanationEn: "Mim and Nun help you hear nasal resonance in Arabic. They are everywhere in Quranic recitation and everyday speech.",
        explanationUr: "میم اور نون میں ناک کی گونج ہوتی ہے۔ یہ قرآن کی تلاوت اور روزمرہ گفتگو دونوں میں بہت آتے ہیں۔",
        quranicExample: word("نَعْبُدُ", "na'budu", "we worship", "ہم عبادت کرتے ہیں"),
        conversationExample: word("مَاء", "ma'", "water", "پانی"),
        reviewWords: [word("م", "mim", "m sound", "م کی آواز"), word("ن", "nun", "n sound", "ن کی آواز")],
      }),
      flashcardLesson({
        title: "Ha & Waw",
        titleAr: "الهاء والواو",
        prompt: "ه و",
        answer: "Ha is a soft h sound; Waw can act as a consonant or a long vowel.",
        focus: word("ه و", "ha, waw", "A light breath letter and a flexible vowel letter.", "ایک نرم حرف اور ایک لچکدار مصوت حرف۔"),
        hook: word("هُوَ", "huwa", "he", "وہ"),
        explanationEn: "Do not confuse this Ha with the deeper Ha you learned earlier. Waw is especially important because it also helps form long uu sounds.",
        explanationUr: "اس ہاء کو پہلے والے گلے کے حاء سے نہ ملائیں۔ واو بھی بہت اہم ہے کیونکہ یہ لمبی uu آواز بھی بناتا ہے۔",
        quranicExample: word("وَهُوَ", "wa huwa", "and He", "اور وہ"),
        conversationExample: word("هَدِيَّة", "hadiyyah", "gift", "تحفہ"),
        reviewWords: [word("ه", "ha", "soft h", "نرم ہ"), word("و", "waw", "w / long uu", "و یا لمبی uu")],
      }),
      flashcardLesson({
        title: "Ya",
        titleAr: "الياء",
        prompt: "ي",
        answer: "Ya is the final alphabet letter and also helps make a long ii sound.",
        focus: word("ي", "ya", "The final Arabic letter and a long vowel helper.", "عربی کا آخری حرف اور لمبی ii آواز کا مددگار۔"),
        hook: word("يَوْم", "yawm", "day", "دن"),
        explanationEn: "Ya appears in the beginning, middle, and end of words. It also stretches kasra into the long ii sound.",
        explanationUr: "یاء لفظ کے شروع، درمیان، اور آخر میں آتی ہے۔ یہ کسرہ کو کھینچ کر لمبی ii آواز بھی بناتی ہے۔",
        quranicExample: word("إِيَّاكَ", "iyyaka", "You alone", "صرف تجھ کو"),
        conversationExample: word("يَد", "yad", "hand", "ہاتھ"),
        reviewWords: [word("ي", "ya", "y / long ii", "ی یا لمبی ii")],
      }),
      flashcardLesson({
        title: "Hamza",
        titleAr: "الهمزة",
        prompt: "ء أ إ آ ؤ ئ",
        answer: "Hamza is the glottal stop and can appear in several written forms.",
        focus: word("ء", "hamza", "A sharp catch in the throat.", "گلے کی اچانک بندش والی آواز۔"),
        hook: word("إِيَّاكَ", "iyyaka", "You alone", "صرف تجھ کو"),
        explanationEn: "Hamza is not a new alphabet family but a sound marker. Learn its different seats so you can recognize it wherever it lands.",
        explanationUr: "ہمزہ کوئی الگ حروفی خاندان نہیں بلکہ ایک خاص آواز ہے۔ اس کی مختلف شکلیں سیکھیں تاکہ ہر جگہ اسے پہچان سکیں۔",
        quranicExample: word("أَحَد", "ahad", "one / unique", "ایک"),
        conversationExample: word("أُمّ", "umm", "mother", "ماں"),
        reviewWords: [word("أ", "a", "hamza on alif", "الف پر ہمزہ"), word("إ", "i", "hamza below alif", "الف کے نیچے ہمزہ")],
      }),
      flashcardLesson({
        title: "Lam-Alif",
        titleAr: "لام ألف",
        prompt: "لا",
        answer: "Lam-Alif is a required ligature, not a separate alphabet letter.",
        focus: word("لا", "la", "The combined Lam-Alif shape.", "لام اور الف کی مشترک شکل۔"),
        hook: word("لَا إِلٰهَ إِلَّا اللّٰه", "la ilaha illa Allah", "There is no god but Allah", "اللہ کے سوا کوئی معبود نہیں"),
        explanationEn: "When Lam meets Alif, Arabic writes them as one joined shape. You will see this form all the time in reading practice.",
        explanationUr: "جب لام کے بعد الف آئے تو عربی میں دونوں اکثر ایک خاص مشترک شکل میں لکھے جاتے ہیں۔ پڑھائی میں یہ شکل بہت نظر آئے گی۔",
        quranicExample: word("لَا رَيْبَ", "la rayba", "no doubt", "کوئی شک نہیں"),
        conversationExample: word("لَا", "la", "no", "نہیں"),
        reviewWords: [word("لا", "la", "no", "نہیں")],
      }),
      quizLesson({
        title: "Sun & Moon Letters",
        titleAr: "الحروف الشمسية والقمرية",
        type: "MULTIPLE_CHOICE",
        question: "Why does the ل in ال disappear in ash-shams but stay clear in al-qamar?",
        questionUr: "اَشَّمْس میں ال کا لام کیوں غائب ہو جاتا ہے جبکہ القمر میں واضح رہتا ہے؟",
        answer: "Because ش is a sun letter and ق is a moon letter.",
        options: [
          "Because ش is a sun letter and ق is a moon letter.",
          "Because every word with ال hides the ل.",
          "Because ق is a sun letter and ش is a moon letter.",
          "Because the vowel marks remove the ل."
        ],
        hook: word("الشَّمْس / القَمَر", "ash-shams / al-qamar", "the sun / the moon", "سورج / چاند"),
        focus: word("ال", "al-", "The Arabic definite article.", "عربی کا معرفہ بنانے والا حرف۔"),
        explanationEn: "Sun letters absorb the Lam sound, while moon letters let you pronounce it clearly.",
        explanationUr: "شمسی حروف میں لام کی آواز جذب ہو جاتی ہے، جبکہ قمری حروف میں لام واضح پڑھا جاتا ہے۔",
        quranicExample: word("النَّاس", "an-nas", "the people", "لوگ"),
        conversationExample: word("القَلَم", "al-qalam", "the pen", "وہ قلم"),
        reviewWords: [word("الشَّمْس", "ash-shams", "the sun", "سورج"), word("القَمَر", "al-qamar", "the moon", "چاند")],
      }),
      quizLesson({
        title: "Full Alphabet Review",
        titleAr: "مراجعة الحروف كاملة",
        type: "FILL_BLANK",
        question: "Which of these is the letter Qaf?",
        questionUr: "ان میں سے قاف کون سا حرف ہے؟",
        answer: "ق",
        options: ["ف", "ق", "ك", "غ"],
        hook: word("قُرْآن", "Qur'an", "Quran", "قرآن"),
        focus: word("ا-ي", "alif to ya", "The full Arabic alphabet.", "پورا عربی حروف تہجی۔"),
        explanationEn: "This checkpoint confirms that you can recognize letters from across the entire alphabet.",
        explanationUr: "یہ مرحلہ دیکھتا ہے کہ آپ پورے حروف تہجی میں سے حروف کو درست پہچان سکتے ہیں یا نہیں۔",
        quranicExample: word("غَفُور", "ghafur", "Forgiving", "بخشنے والا"),
        conversationExample: word("كِتَاب", "kitab", "book", "کتاب"),
        reviewWords: [word("ق", "qaf", "qaf", "قاف"), word("ي", "ya", "ya", "یاء")],
      }),
      quizLesson({
        title: "Reading Practice",
        titleAr: "تدريب القراءة",
        type: "FILL_BLANK",
        question: "Which word below reads as bayt (house)?",
        questionUr: "نیچے دیے گئے الفاظ میں bayt (گھر) کون سا ہے؟",
        answer: "بَيْت",
        options: ["بَيْت", "بَاب", "قَلَم", "مَاء"],
        hook: word("بَيْت", "bayt", "house", "گھر"),
        focus: word("بَيْت", "bayt", "A simple fully readable word.", "ایک سادہ پڑھا جانے والا لفظ۔"),
        explanationEn: "Now bring the whole alphabet together and identify short, readable Arabic words from left to right.",
        explanationUr: "اب پورے حروف کو ملا کر بائیں سے دائیں سادہ عربی الفاظ پہچاننے کی مشق کریں۔",
        quranicExample: word("كِتَاب", "kitab", "book", "کتاب"),
        conversationExample: word("بَيْت", "bayt", "house", "گھر"),
        reviewWords: [word("بَيْت", "bayt", "house", "گھر"), word("بَاب", "bab", "door", "دروازہ")],
      }),
    ]
  ),
  chapter(
    4,
    "Short Vowels (Harakat)",
    "الحركات القصيرة",
    "Makkah · Learn the short vowel marks that make Arabic readable out loud.",
    0.3,
    0.28,
    [
      flashcardLesson({
        title: "Fatha",
        titleAr: "الفتحة",
        prompt: "بَ",
        answer: "Fatha gives the short a sound: ba.",
        focus: word("بَ", "ba", "Ba with fatha.", "فتحة کے ساتھ با۔"),
        hook: word("رَحْمَة", "rahmah", "mercy", "رحمت"),
        explanationEn: "Fatha sits above the letter and opens the mouth for a short a sound.",
        explanationUr: "فتحة حرف کے اوپر آتی ہے اور منہ کو کھول کر چھوٹی a آواز پیدا کرتی ہے۔",
        quranicExample: word("هَدَى", "hada", "He guided", "اس نے ہدایت دی"),
        conversationExample: word("بَاب", "bab", "door", "دروازہ"),
        reviewWords: [word("فَتْحَة", "fathah", "short a mark", "زبر")],
      }),
      flashcardLesson({
        title: "Kasra",
        titleAr: "الكسرة",
        prompt: "بِ",
        answer: "Kasra gives the short i sound: bi.",
        focus: word("بِ", "bi", "Ba with kasra.", "کسرہ کے ساتھ با۔"),
        hook: word("بِسْمِ", "bismi", "in the name of", "نام سے"),
        explanationEn: "Kasra sits below the letter and narrows the sound into a short i.",
        explanationUr: "کسرہ حرف کے نیچے آتی ہے اور آواز کو چھوٹا i بنا دیتی ہے۔",
        quranicExample: word("بِرَبِّ", "bi-rabb", "with / by the Lord", "رب کے ساتھ"),
        conversationExample: word("بِنْت", "bint", "girl", "لڑکی"),
        reviewWords: [word("كَسْرَة", "kasrah", "short i mark", "زیر")],
      }),
      flashcardLesson({
        title: "Damma",
        titleAr: "الضمة",
        prompt: "بُ",
        answer: "Damma gives the short u sound: bu.",
        focus: word("بُ", "bu", "Ba with damma.", "ضمہ کے ساتھ با۔"),
        hook: word("قُلْ", "qul", "say", "کہہ دو"),
        explanationEn: "Damma curls above the letter and rounds the lips for a short u sound.",
        explanationUr: "ضمہ حرف کے اوپر آتی ہے اور ہونٹوں کو گول کر کے چھوٹی u آواز دیتی ہے۔",
        quranicExample: word("هُوَ", "huwa", "he", "وہ"),
        conversationExample: word("كُرْسِيّ", "kursiyy", "chair", "کرسی"),
        reviewWords: [word("ضَمَّة", "dammah", "short u mark", "پیش")],
      }),
      flashcardLesson({
        title: "Sukun",
        titleAr: "السكون",
        prompt: "بْ",
        answer: "Sukun means the letter rests with no vowel sound.",
        focus: word("بْ", "b", "A consonant at rest.", "بغیر حرکت کے ساکن حرف۔"),
        hook: word("قُلْ", "qul", "say", "کہہ دو"),
        explanationEn: "Sukun tells you to stop the vowel. The consonant remains, but it rests quietly.",
        explanationUr: "سکون بتاتا ہے کہ حرف پر کوئی حرکت نہیں۔ حرف اپنی آواز کے ساتھ رکتا ہے مگر اس پر مصوت نہیں آتا۔",
        quranicExample: word("الْحَمْد", "al-hamd", "the praise", "سب تعریف"),
        conversationExample: word("بْن", "bn", "consonant cluster practice", "ساکن حرف کی مشق"),
        reviewWords: [word("سُكُون", "sukun", "silent mark", "جزم")],
      }),
      flashcardLesson({
        title: "Shadda",
        titleAr: "الشدة",
        prompt: "بّ",
        answer: "Shadda doubles the letter sound.",
        focus: word("بّ", "bb", "A doubled consonant.", "دوہرا پڑھا جانے والا حرف۔"),
        hook: word("رَبّ", "rabb", "Lord", "رب"),
        explanationEn: "When you see shadda, hold the consonant slightly longer as if the letter appears twice.",
        explanationUr: "شدہ دیکھ کر حرف کو ذرا زیادہ روک کر پڑھیں، جیسے وہ حرف دو مرتبہ آیا ہو۔",
        quranicExample: word("إِيَّاكَ", "iyyaka", "You alone", "صرف تجھ کو"),
        conversationExample: word("أُمّ", "umm", "mother", "ماں"),
        reviewWords: [word("شَدَّة", "shaddah", "doubling mark", "تشدید")],
      }),
      quizLesson({
        title: "Reading with Harakat",
        titleAr: "القراءة بالحركات",
        type: "FILL_BLANK",
        question: "Which word below reads as kitabun (a book)?",
        questionUr: "نیچے دیے گئے اختیارات میں kitabun (ایک کتاب) کون سا ہے؟",
        answer: "كِتَابٌ",
        options: ["كِتَابٌ", "كُتُب", "بَيْت", "رَبّ"],
        hook: word("بَيْتٌ، كِتَابٌ", "baytun, kitabun", "a house, a book", "ایک گھر، ایک کتاب"),
        focus: word("كِتَابٌ", "kitabun", "a book", "ایک کتاب"),
        explanationEn: "This reading lesson checks whether you can combine letters with their short vowel marks smoothly.",
        explanationUr: "یہ سبق دیکھتا ہے کہ آپ حروف اور ان کی حرکات کو ملا کر روانی سے پڑھ سکتے ہیں یا نہیں۔",
        quranicExample: word("صِرَاط", "sirat", "path", "راستہ"),
        conversationExample: word("بَيْت", "bayt", "house", "گھر"),
        reviewWords: [word("كِتَابٌ", "kitabun", "a book", "ایک کتاب"), word("بَيْتٌ", "baytun", "a house", "ایک گھر")],
      }),
    ]
  ),
  chapter(
    5,
    "Long Vowels & Tanwin",
    "المدود والتنوين",
    "Makkah · Stretch short vowels into long ones and recognize the three tanwin endings.",
    0.36,
    0.32,
    [
      flashcardLesson({
        title: "Long Alif",
        titleAr: "المد بالألف",
        prompt: "بَا",
        answer: "A long alif stretches fatha into aa: baa.",
        focus: word("بَا", "baa", "A long aa sound.", "لمبی aa آواز۔"),
        hook: word("قَالَ", "qala", "he said", "اس نے کہا"),
        explanationEn: "When fatha is followed by alif, the sound stretches. Hold it for about twice the short vowel length.",
        explanationUr: "جب فتحہ کے بعد الف آئے تو آواز لمبی ہو جاتی ہے۔ اسے مختصر حرکت سے تقریباً دو گنا لمبا پڑھیں۔",
        quranicExample: word("كِتَاب", "kitab", "book", "کتاب"),
        conversationExample: word("بَاب", "bab", "door", "دروازہ"),
        reviewWords: [word("ا", "alif", "long aa carrier", "لمبی aa کا حرف")],
      }),
      flashcardLesson({
        title: "Long Ya",
        titleAr: "المد بالياء",
        prompt: "بِي",
        answer: "A long ya stretches kasra into ii: bii.",
        focus: word("بِي", "bii", "A long ii sound.", "لمبی ii آواز۔"),
        hook: word("فِيهِ", "fihi", "in it", "اس میں"),
        explanationEn: "Kasra followed by Ya gives a long ii sound. Listen for the smooth stretch rather than a clipped short vowel.",
        explanationUr: "کسرہ کے بعد یاء آئے تو لمبی ii آواز بنتی ہے۔ اسے چھوٹا کاٹنے کے بجائے ہموار کھینچ کر پڑھیں۔",
        quranicExample: word("فِي", "fi", "in", "میں"),
        conversationExample: word("كَبِير", "kabir", "big", "بڑا"),
        reviewWords: [word("ي", "ya", "long ii carrier", "لمبی ii کا حرف")],
      }),
      flashcardLesson({
        title: "Long Waw",
        titleAr: "المد بالواو",
        prompt: "بُو",
        answer: "A long waw stretches damma into uu: buu.",
        focus: word("بُو", "buu", "A long uu sound.", "لمبی uu آواز۔"),
        hook: word("نُور", "nur", "light", "نور"),
        explanationEn: "Damma followed by Waw creates a long uu sound. Round the lips and sustain the sound smoothly.",
        explanationUr: "ضمہ کے بعد واو آئے تو لمبی uu آواز بنتی ہے۔ ہونٹ گول رکھ کر آواز کو نرمی سے کھینچیں۔",
        quranicExample: word("يَقُولُ", "yaqulu", "he says", "وہ کہتا ہے"),
        conversationExample: word("سُوق", "suq", "market", "بازار"),
        reviewWords: [word("و", "waw", "long uu carrier", "لمبی uu کا حرف")],
      }),
      flashcardLesson({
        title: "Tanwin Fath",
        titleAr: "تنوين الفتح",
        prompt: "ـً",
        answer: "Tanwin fath gives the indefinite an ending.",
        focus: word("كِتَابًا", "kitaban", "a book (accusative)", "ایک کتاب (نصب)"),
        hook: word("عِلْمًا", "'ilman", "knowledge", "علم"),
        explanationEn: "Tanwin fath marks an indefinite noun with an an sound, often when the word is in the accusative case.",
        explanationUr: "تنوین فتح کسی نکرہ اسم کے آخر میں an کی آواز دیتی ہے، خاص طور پر جب اسم منصوب ہو۔",
        quranicExample: word("رَبِّ زِدْنِي عِلْمًا", "rabbi zidni 'ilma", "My Lord, increase me in knowledge", "میرے رب، میرا علم بڑھا دے"),
        conversationExample: word("أُرِيدُ كِتَابًا", "uridu kitaban", "I want a book", "مجھے ایک کتاب چاہیے"),
        reviewWords: [word("ـً", "an", "tanwin fath", "دو زبر")],
      }),
      flashcardLesson({
        title: "Tanwin Kasr",
        titleAr: "تنوين الكسر",
        prompt: "ـٍ",
        answer: "Tanwin kasr gives the indefinite in ending.",
        focus: word("كِتَابٍ", "kitabin", "a book (after a preposition)", "ایک کتاب (جر)"),
        hook: word("فِي بَيْتٍ", "fi baytin", "in a house", "ایک گھر میں"),
        explanationEn: "Tanwin kasr produces an in sound and often appears after prepositions when the noun is indefinite.",
        explanationUr: "تنوین کسر in کی آواز دیتی ہے اور اکثر حروفِ جار کے بعد نکرہ اسم کے ساتھ آتی ہے۔",
        quranicExample: word("فِي ضَلَالٍ", "fi dalalin", "in error", "گمراہی میں"),
        conversationExample: word("فِي سُوقٍ", "fi suqin", "in a market", "ایک بازار میں"),
        reviewWords: [word("ـٍ", "in", "tanwin kasr", "دو زیر")],
      }),
      flashcardLesson({
        title: "Tanwin Damm",
        titleAr: "تنوين الضم",
        prompt: "ـٌ",
        answer: "Tanwin damm gives the indefinite un ending.",
        focus: word("كِتَابٌ", "kitabun", "a book", "ایک کتاب"),
        hook: word("هُدًى لِّلْمُتَّقِينَ", "hudan lil-muttaqin", "guidance for the mindful", "پرہیزگاروں کے لیے ہدایت"),
        explanationEn: "Tanwin damm marks an indefinite noun with an un sound, often when it is the subject of the sentence.",
        explanationUr: "تنوین ضم نکرہ اسم کے آخر میں un کی آواز دیتی ہے، اور اکثر یہ جملے کے مبتدا یا فاعل کے ساتھ آتی ہے۔",
        quranicExample: word("رَجُلٌ", "rajulun", "a man", "ایک آدمی"),
        conversationExample: word("هٰذَا بَيْتٌ", "hadha baytun", "this is a house", "یہ ایک گھر ہے"),
        reviewWords: [word("ـٌ", "un", "tanwin damm", "دو پیش")],
      }),
    ]
  ),
  chapter(
    6,
    "Bismillah & Salah Vocabulary",
    "البسملة ومفردات الصلاة",
    "Madinah · Begin your word bank with Bismillah, Al-Fatihah, and common salah phrases.",
    0.46,
    0.24,
    [
      flashcardLesson({
        title: "Bismillah word by word",
        titleAr: "بسم الله كلمة كلمة",
        prompt: "بِسْمِ اللّٰهِ الرَّحْمٰنِ الرَّحِيمِ",
        answer: "Bismillah means: In the name of Allah, the Entirely Merciful, the Especially Merciful.",
        focus: word("بِسْمِ اللّٰهِ", "bismillahi", "in the name of Allah", "اللہ کے نام سے"),
        hook: word("بِسْمِ اللّٰهِ الرَّحْمٰنِ الرَّحِيمِ", "Bismillahir-Rahmanir-Rahim", "In the name of Allah, the Most Merciful, the Especially Merciful", "اللہ کے نام سے جو نہایت مہربان بہت رحم والا ہے"),
        explanationEn: "Break Bismillah into its parts: bi = with/in, ism = name, Allah = Allah, and the two mercy names that follow.",
        explanationUr: "بسم اللہ کو حصوں میں تقسیم کریں: بِ = کے ساتھ/سے، اسم = نام، اللہ = اللہ، پھر اس کے بعد رحمت کے دو صفاتی نام آتے ہیں۔",
        quranicExample: word("الرَّحْمٰن", "ar-Rahman", "The Entirely Merciful", "نہایت مہربان"),
        conversationExample: word("بِسْمِ اللّٰهِ", "bismillah", "I begin in Allah's name", "میں اللہ کے نام سے شروع کرتا ہوں"),
        reviewWords: [word("اسم", "ism", "name", "نام"), word("اللّٰه", "Allah", "Allah", "اللہ"), word("رَحِيم", "rahim", "merciful", "رحم والا")],
      }),
      flashcardLesson({
        title: "Alhamdulillah",
        titleAr: "الحمد لله",
        prompt: "الْحَمْدُ لِلّٰهِ",
        answer: "Alhamdulillah means: All praise belongs to Allah.",
        focus: word("الْحَمْدُ", "al-hamdu", "all praise", "سب تعریف"),
        hook: word("الْحَمْدُ لِلّٰهِ", "alhamdulillah", "All praise is for Allah", "سب تعریف اللہ کے لیے ہے"),
        explanationEn: "This phrase joins praise with belonging: hamd means praise, and li-llah shows that the praise belongs to Allah.",
        explanationUr: "اس جملے میں تعریف اور نسبت دونوں ہیں۔ حمد کا مطلب تعریف ہے اور لِلّٰهِ بتاتا ہے کہ یہ تعریف اللہ کے لیے ہے۔",
        quranicExample: word("رَبِّ الْعَالَمِين", "Rabbil-'alamin", "Lord of the worlds", "تمام جہانوں کا رب"),
        conversationExample: word("الحمد لله، أنا بخير", "alhamdulillah, ana bikhayr", "Praise be to Allah, I am well", "الحمد للہ، میں خیریت سے ہوں"),
        reviewWords: [word("حَمْد", "hamd", "praise", "تعریف"), word("لِ", "li", "for / belonging to", "کے لیے")],
      }),
      flashcardLesson({
        title: "Allahu Akbar",
        titleAr: "الله أكبر",
        prompt: "اللّٰهُ أَكْبَرُ",
        answer: "Allahu Akbar means: Allah is greater / the greatest.",
        focus: word("أَكْبَر", "akbar", "greater / greatest", "زیادہ بڑا / سب سے بڑا"),
        hook: word("اللّٰهُ أَكْبَرُ", "Allahu Akbar", "Allah is greater", "اللہ سب سے بڑا ہے"),
        explanationEn: "Akbar is a comparative form. In salah and adhan it reminds you that Allah is greater than everything competing for your attention.",
        explanationUr: "اکبر ایک تقابلی صیغہ ہے۔ نماز اور اذان میں یہ یاد دلاتا ہے کہ اللہ ہر چیز سے بڑا ہے۔",
        quranicExample: word("اللّٰهُ", "Allahu", "Allah", "اللہ"),
        conversationExample: word("اللّٰهُ أَكْبَرُ", "Allahu Akbar", "Allah is greater", "اللہ سب سے بڑا ہے"),
        reviewWords: [word("كَبِير", "kabir", "big", "بڑا"), word("أَكْبَر", "akbar", "greater", "زیادہ بڑا")],
      }),
      flashcardLesson({
        title: "Subhanallah",
        titleAr: "سبحان الله",
        prompt: "سُبْحَانَ اللّٰهِ",
        answer: "Subhanallah means: Glory be to Allah / Allah is far above all نقص.",
        focus: word("سُبْحَان", "subhan", "glory / transcendence", "پاکی اور بلندی"),
        hook: word("سُبْحَانَ اللّٰهِ", "Subhanallah", "Glory be to Allah", "اللہ پاک ہے"),
        explanationEn: "This phrase declares Allah free from every imperfection. It is one of the most repeated words in dhikr and salah.",
        explanationUr: "یہ کلمہ اللہ کو ہر نقص سے پاک قرار دیتا ہے۔ ذکر اور نماز میں یہ بہت کثرت سے آتا ہے۔",
        quranicExample: word("سُبْحَانَ الَّذِي", "subhana alladhi", "Glory be to the One who...", "پاک ہے وہ ذات جو..."),
        conversationExample: word("سُبْحَانَ اللّٰهِ! مَا أَجْمَلَهُ", "subhanallah! ma ajmalahu", "Glory be to Allah! How beautiful it is", "سبحان اللہ! یہ کتنا خوبصورت ہے"),
        reviewWords: [word("سُبْحَان", "subhan", "glory", "پاکی"), word("اللّٰه", "Allah", "Allah", "اللہ")],
      }),
      flashcardLesson({
        title: "Salah phrases 1",
        titleAr: "ألفاظ الصلاة ١",
        prompt: "رَبَّنَا • رَحِيم • عَظِيم",
        answer: "These words mean: our Lord, merciful, great.",
        focus: word("رَبَّنَا", "rabbana", "our Lord", "ہمارا رب"),
        hook: word("رَبَّنَا", "rabbana", "our Lord", "ہمارا رب"),
        explanationEn: "These are high-frequency salah words. Rabbana calls on Allah directly, while rahim and 'azim describe His mercy and greatness.",
        explanationUr: "یہ نماز میں بہت آنے والے الفاظ ہیں۔ ربنا اللہ کو پکارنے کے لیے آتا ہے، جبکہ رحیم اور عظیم اس کی صفات بتاتے ہیں۔",
        quranicExample: word("رَبَّنَا اغْفِرْ لَنَا", "rabbana ighfir lana", "Our Lord, forgive us", "اے ہمارے رب، ہمیں بخش دے"),
        conversationExample: word("هٰذَا أَمْرٌ عَظِيم", "hadha amrun 'azim", "This is a great matter", "یہ ایک بڑی بات ہے"),
        reviewWords: [word("رَحِيم", "rahim", "merciful", "رحم والا"), word("عَظِيم", "'azim", "great", "عظیم")],
      }),
      flashcardLesson({
        title: "Salah phrases 2",
        titleAr: "ألفاظ الصلاة ٢",
        prompt: "سَمِعَ • حَمِدَ • سَجَدَ",
        answer: "These words mean: heard, praised, prostrated.",
        focus: word("سَجَدَ", "sajada", "he prostrated", "اس نے سجدہ کیا"),
        hook: word("سَمِعَ اللّٰهُ لِمَنْ حَمِدَهُ", "sami'a Allahu liman hamidah", "Allah hears the one who praises Him", "اللہ اس کی سنتا ہے جو اس کی تعریف کرے"),
        explanationEn: "These are basic action words from salah language. They help you hear what is happening in worship, not just repeat the sounds.",
        explanationUr: "یہ نماز کی زبان کے بنیادی فعلی الفاظ ہیں۔ ان سے آپ صرف الفاظ دہرانے کے بجائے معنی بھی سمجھنے لگتے ہیں۔",
        quranicExample: word("سَجَدَ", "sajada", "he prostrated", "اس نے سجدہ کیا"),
        conversationExample: word("حَمِدْتُ اللّٰهَ", "hamidtu Allah", "I praised Allah", "میں نے اللہ کی حمد کی"),
        reviewWords: [word("سَمِعَ", "sami'a", "he heard", "اس نے سنا"), word("حَمِدَ", "hamida", "he praised", "اس نے تعریف کی"), word("سَجَدَ", "sajada", "he prostrated", "اس نے سجدہ کیا")],
      }),
      flashcardLesson({
        title: "Al-Fatiha word by word",
        titleAr: "الفاتحة كلمة كلمة",
        prompt: "سُورَةُ الفَاتِحَة",
        answer: "This lesson introduces the core word bank of Al-Fatiha.",
        focus: word("الفَاتِحَة", "al-Fatihah", "the Opening", "سورہ فاتحہ"),
        hook: word("اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ", "ihdina s-sirat al-mustaqim", "Guide us to the straight path", "ہمیں سیدھا راستہ دکھا"),
        explanationEn: "Al-Fatiha is the best first Quranic passage to study word by word because you repeat it every day and it contains core grammar and vocabulary.",
        explanationUr: "سورہ فاتحہ لفظ بہ لفظ سیکھنے کے لیے بہترین آغاز ہے کیونکہ آپ اسے ہر روز دہراتے ہیں اور اس میں بنیادی الفاظ اور قواعد موجود ہیں۔",
        quranicExample: word("مَالِكِ يَوْمِ الدِّين", "maliki yawm id-din", "Master of the Day of Judgment", "روزِ جزا کے مالک"),
        conversationExample: word("صِرَاط", "sirat", "path", "راستہ"),
        reviewWords: [word("اهْدِنَا", "ihdina", "guide us", "ہمیں ہدایت دے"), word("صِرَاط", "sirat", "path", "راستہ"), word("الدِّين", "ad-din", "the religion / judgment", "دین / جزا")],
      }),
      quizLesson({
        title: "Review: Salah vocab",
        titleAr: "مراجعة مفردات الصلاة",
        type: "MULTIPLE_CHOICE",
        question: "What does رَبَّنَا mean?",
        questionUr: "رَبَّنَا کا کیا مطلب ہے؟",
        answer: "Our Lord",
        options: ["Our Lord", "Our book", "Our house", "Our day"],
        hook: word("رَبَّنَا آتِنَا", "rabbana atina", "Our Lord, grant us", "اے ہمارے رب، ہمیں عطا فرما"),
        focus: word("رَبَّنَا", "rabbana", "our Lord", "ہمارا رب"),
        explanationEn: "This review checks that your salah vocabulary is turning into meaning, not just memorized sounds.",
        explanationUr: "یہ دہرائی دیکھتی ہے کہ آپ کی نماز کی لغت صرف یاد کی ہوئی آوازیں نہیں بلکہ معنی بھی بن رہی ہے۔",
        quranicExample: word("الْحَمْدُ لِلّٰهِ", "alhamdulillah", "All praise is for Allah", "سب تعریف اللہ کے لیے ہے"),
        conversationExample: word("الحمد لله", "alhamdulillah", "Praise be to Allah", "الحمد للہ"),
        reviewWords: [word("رَبَّنَا", "rabbana", "our Lord", "ہمارا رب"), word("عَظِيم", "'azim", "great", "عظیم")],
      }),
    ]
  ),
  chapter(
    7,
    "People & Pronouns",
    "الضمائر والناس",
    "Madinah · Build a starter pronoun system so you can talk about yourself and other people.",
    0.52,
    0.28,
    [
      flashcardLesson({
        title: "He / She / They",
        titleAr: "هو / هي / هم",
        prompt: "هُوَ • هِيَ • هُمْ",
        answer: "These pronouns mean: he, she, they.",
        focus: word("هُوَ", "huwa", "he", "وہ"),
        hook: word("هُوَ اللّٰهُ أَحَد", "huwa Allahu ahad", "He is Allah, One", "وہ اللہ ایک ہے"),
        explanationEn: "Arabic pronouns change for gender and number. Start by recognizing the most common third-person set.",
        explanationUr: "عربی میں ضمیر جنس اور عدد کے ساتھ بدلتی ہے۔ پہلے تیسرے شخص کی سب سے عام ضمیریں یاد کریں۔",
        quranicExample: word("هُوَ", "huwa", "he / He", "وہ"),
        conversationExample: word("هِيَ طَالِبَة", "hiya talibah", "she is a student", "وہ طالبہ ہے"),
        reviewWords: [word("هُوَ", "huwa", "he", "وہ"), word("هِيَ", "hiya", "she", "وہ"), word("هُمْ", "hum", "they", "وہ سب")],
      }),
      flashcardLesson({
        title: "I / We",
        titleAr: "أنا / نحن",
        prompt: "أَنَا • نَحْنُ",
        answer: "These pronouns mean: I, we.",
        focus: word("أَنَا", "ana", "I", "میں"),
        hook: word("إِيَّاكَ نَعْبُدُ", "iyyaka na'budu", "You alone we worship", "ہم صرف تیری عبادت کرتے ہیں"),
        explanationEn: "First-person pronouns help you speak for yourself and for a group. They appear constantly in duas and introductions.",
        explanationUr: "یہ ضمیر آپ کو اپنے لیے اور جماعت کے لیے بولنا سکھاتی ہیں۔ دعاؤں اور تعارف میں یہ بہت آتی ہیں۔",
        quranicExample: word("نَحْنُ", "nahnu", "we", "ہم"),
        conversationExample: word("أَنَا مِنْ بَاكِسْتَان", "ana min Pakistan", "I am from Pakistan", "میں پاکستان سے ہوں"),
        reviewWords: [word("أَنَا", "ana", "I", "میں"), word("نَحْنُ", "nahnu", "we", "ہم")],
      }),
      flashcardLesson({
        title: "You (singular / plural)",
        titleAr: "أنتَ / أنتِ / أنتم",
        prompt: "أَنْتَ • أَنْتِ • أَنْتُمْ",
        answer: "These pronouns mean: you (masc.), you (fem.), you all.",
        focus: word("أَنْتَ", "anta", "you (masculine singular)", "تم"),
        hook: word("أَنْتَ رَبِّي", "anta rabbi", "You are my Lord", "تو میرا رب ہے"),
        explanationEn: "Arabic distinguishes who you are speaking to. Gender matters even in very short sentences.",
        explanationUr: "عربی میں مخاطَب کے لحاظ سے ضمیر بدلتی ہے۔ مختصر جملوں میں بھی جنس کا فرق اہم ہوتا ہے۔",
        quranicExample: word("أَنْتَ", "anta", "You", "تو"),
        conversationExample: word("أَنْتِ طَيِّبَة", "anti tayyibah", "you are kind", "تم اچھی ہو"),
        reviewWords: [word("أَنْتَ", "anta", "you (m.)", "تم"), word("أَنْتِ", "anti", "you (f.)", "تم"), word("أَنْتُمْ", "antum", "you all", "آپ سب")],
      }),
      flashcardLesson({
        title: "Family words",
        titleAr: "ألفاظ العائلة",
        prompt: "أَب • أُمّ • أَخ • أُخْت",
        answer: "These words mean: father, mother, brother, sister.",
        focus: word("أَب", "ab", "father", "والد"),
        hook: word("وَبِالْوَالِدَيْنِ إِحْسَانًا", "wa bil-walidayni ihsana", "and excellence to the parents", "اور والدین کے ساتھ اچھا سلوک"),
        explanationEn: "Family words are high-frequency in both conversation and Islamic vocabulary. Notice how short many of them are.",
        explanationUr: "خاندانی الفاظ گفتگو اور اسلامی زبان دونوں میں بہت استعمال ہوتے ہیں۔ دھیان دیں کہ ان میں سے کئی الفاظ بہت مختصر ہیں۔",
        quranicExample: word("أُمّ", "umm", "mother", "ماں"),
        conversationExample: word("أُخْتِي فِي البَيْت", "ukhti fi al-bayt", "my sister is in the house", "میری بہن گھر میں ہے"),
        reviewWords: [word("أَب", "ab", "father", "والد"), word("أُمّ", "umm", "mother", "ماں"), word("أَخ", "akh", "brother", "بھائی"), word("أُخْت", "ukht", "sister", "بہن")],
      }),
      flashcardLesson({
        title: "People words",
        titleAr: "ألفاظ الناس",
        prompt: "رَجُل • امْرَأَة • وَلَد • بِنْت",
        answer: "These words mean: man, woman, boy, girl.",
        focus: word("رَجُل", "rajul", "man", "آدمی"),
        hook: word("النَّاس", "an-nas", "the people", "لوگ"),
        explanationEn: "These are core nouns for describing people around you. They will later help with gender agreement lessons too.",
        explanationUr: "یہ آس پاس کے لوگوں کے لیے بنیادی اسماء ہیں۔ بعد میں یہی الفاظ جنس کے قواعد میں بھی کام آئیں گے۔",
        quranicExample: word("النَّاس", "an-nas", "the people", "لوگ"),
        conversationExample: word("هٰذِهِ بِنْتٌ صَغِيرَة", "hadhihi bintun saghirah", "this is a young girl", "یہ ایک چھوٹی لڑکی ہے"),
        reviewWords: [word("رَجُل", "rajul", "man", "آدمی"), word("امْرَأَة", "imra'ah", "woman", "عورت"), word("وَلَد", "walad", "boy", "لڑکا"), word("بِنْت", "bint", "girl", "لڑکی")],
      }),
      quizLesson({
        title: "Review: Pronouns",
        titleAr: "مراجعة الضمائر",
        type: "FILL_BLANK",
        question: "Which pronoun means 'we'?",
        questionUr: "کون سی ضمیر 'ہم' کے معنی دیتی ہے؟",
        answer: "نَحْنُ",
        options: ["أَنَا", "نَحْنُ", "هُوَ", "أَنْتَ"],
        hook: word("نَحْنُ", "nahnu", "we", "ہم"),
        focus: word("الضمائر", "ad-dama'ir", "pronouns", "ضمیر"),
        explanationEn: "This review checks whether you can connect the Arabic pronoun form to the person it refers to.",
        explanationUr: "یہ دہرائی دیکھتی ہے کہ آپ عربی ضمیر کو درست شخص کے ساتھ جوڑ سکتے ہیں یا نہیں۔",
        quranicExample: word("إِيَّاكَ نَعْبُدُ", "iyyaka na'budu", "You alone we worship", "ہم صرف تیری عبادت کرتے ہیں"),
        conversationExample: word("أَنَا طَالِب", "ana talib", "I am a student", "میں طالب علم ہوں"),
        reviewWords: [word("أَنَا", "ana", "I", "میں"), word("نَحْنُ", "nahnu", "we", "ہم"), word("هُوَ", "huwa", "he", "وہ")],
      }),
    ]
  ),
  chapter(
    8,
    "The World Around Us",
    "العالم من حولنا",
    "Madinah · Learn core nouns for nature, time, place, number, and color.",
    0.58,
    0.32,
    [
      flashcardLesson({
        title: "Nature",
        titleAr: "الطبيعة",
        prompt: "سَمَاء • أَرْض • شَمْس • قَمَر",
        answer: "These words mean: sky, earth, sun, moon.",
        focus: word("سَمَاء", "sama'", "sky", "آسمان"),
        hook: word("رَبُّ السَّمَاوَاتِ وَالأَرْض", "rabbus-samawati wal-ard", "Lord of the heavens and the earth", "آسمانوں اور زمین کا رب"),
        explanationEn: "These are foundational Quranic nouns and also the easiest way to begin describing the world around you.",
        explanationUr: "یہ قرآن کے بنیادی اسماء ہیں اور آپ کے آس پاس کی دنیا کو بیان کرنے کی اچھی ابتدا بھی ہیں۔",
        quranicExample: word("شَمْس", "shams", "sun", "سورج"),
        conversationExample: word("القَمَرُ جَمِيل", "al-qamar جميل", "the moon is beautiful", "چاند خوبصورت ہے"),
        reviewWords: [word("سَمَاء", "sama'", "sky", "آسمان"), word("أَرْض", "ard", "earth", "زمین"), word("شَمْس", "shams", "sun", "سورج"), word("قَمَر", "qamar", "moon", "چاند")],
      }),
      flashcardLesson({
        title: "Water & Light",
        titleAr: "الماء والنور",
        prompt: "مَاء • نُور • نَار • ظُلُمَات",
        answer: "These words mean: water, light, fire, darknesses.",
        focus: word("نُور", "nur", "light", "نور"),
        hook: word("اللّٰهُ نُورُ السَّمَاوَاتِ وَالأَرْض", "Allahu nuru s-samawati wal-ard", "Allah is the Light of the heavens and the earth", "اللہ آسمانوں اور زمین کا نور ہے"),
        explanationEn: "These words appear in both physical and spiritual meanings. Quranic Arabic often uses them literally and metaphorically.",
        explanationUr: "یہ الفاظ حقیقی اور معنوی دونوں انداز میں آتے ہیں۔ قرآن میں یہ کبھی ظاہری اور کبھی روحانی معنی میں استعمال ہوتے ہیں۔",
        quranicExample: word("مَاء", "ma'", "water", "پانی"),
        conversationExample: word("أُرِيدُ مَاءً", "uridu ma'an", "I want water", "مجھے پانی چاہیے"),
        reviewWords: [word("مَاء", "ma'", "water", "پانی"), word("نُور", "nur", "light", "نور"), word("نَار", "nar", "fire", "آگ"), word("ظُلُمَات", "zulumat", "darknesses", "تاریکیاں")],
      }),
      flashcardLesson({
        title: "Time words",
        titleAr: "ألفاظ الوقت",
        prompt: "يَوْم • لَيْل • نَهَار • وَقْت",
        answer: "These words mean: day, night, daytime, time.",
        focus: word("يَوْم", "yawm", "day", "دن"),
        hook: word("مَالِكِ يَوْمِ الدِّين", "maliki yawm id-din", "Master of the Day of Judgment", "روز جزا کے مالک"),
        explanationEn: "Time words give you a simple way to talk about routines, worship times, and Quranic scenes.",
        explanationUr: "وقت کے الفاظ آپ کو معمولات، عبادت کے اوقات، اور قرآنی مناظر کو بیان کرنے میں مدد دیتے ہیں۔",
        quranicExample: word("لَيْل", "layl", "night", "رات"),
        conversationExample: word("هٰذَا يَوْمٌ طَوِيل", "hadha yawmun tawil", "this is a long day", "یہ ایک لمبا دن ہے"),
        reviewWords: [word("يَوْم", "yawm", "day", "دن"), word("لَيْل", "layl", "night", "رات"), word("وَقْت", "waqt", "time", "وقت")],
      }),
      flashcardLesson({
        title: "Places",
        titleAr: "الأماكن",
        prompt: "مَسْجِد • بَيْت • مَدِينَة • سُوق",
        answer: "These words mean: mosque, house, city, market.",
        focus: word("مَسْجِد", "masjid", "mosque", "مسجد"),
        hook: word("المَسْجِد الحَرَام", "al-masjid al-haram", "the Sacred Mosque", "مسجد حرام"),
        explanationEn: "Place words become useful immediately in travel, worship, and simple daily descriptions.",
        explanationUr: "جگہوں کے الفاظ سفر، عبادت، اور روزمرہ کے مختصر جملوں میں فوراً کام آتے ہیں۔",
        quranicExample: word("مَسْجِد", "masjid", "mosque", "مسجد"),
        conversationExample: word("أَيْنَ البَيْت؟", "ayna al-bayt?", "where is the house?", "گھر کہاں ہے؟"),
        reviewWords: [word("مَسْجِد", "masjid", "mosque", "مسجد"), word("بَيْت", "bayt", "house", "گھر"), word("مَدِينَة", "madinah", "city", "شہر"), word("سُوق", "suq", "market", "بازار")],
      }),
      flashcardLesson({
        title: "Numbers 1-10",
        titleAr: "الأعداد ١-١٠",
        prompt: "وَاحِد إلى عَشَرَة",
        answer: "This lesson covers the cardinal numbers from 1 to 10.",
        focus: word("وَاحِد", "wahid", "one", "ایک"),
        hook: word("أَحَد", "ahad", "one", "ایک"),
        explanationEn: "Count slowly from one to ten. You do not need perfect speed yet; focus on recognizing the forms and hearing the pattern.",
        explanationUr: "ایک سے دس تک آہستہ آہستہ گنیں۔ ابھی تیزی ضروری نہیں، پہلے شکلیں اور آواز کا نمونہ پہچانیں۔",
        quranicExample: word("أَحَد", "ahad", "one", "ایک"),
        conversationExample: word("عِنْدِي ثَلَاثَةُ كُتُب", "'indi thalathatu kutub", "I have three books", "میرے پاس تین کتابیں ہیں"),
        reviewWords: [word("وَاحِد", "wahid", "one", "ایک"), word("اثْنَان", "ithnan", "two", "دو"), word("ثَلَاثَة", "thalathah", "three", "تین"), word("عَشَرَة", "'asharah", "ten", "دس")],
      }),
      flashcardLesson({
        title: "Colors",
        titleAr: "الألوان",
        prompt: "أَحْمَر • أَبْيَض • أَسْوَد • أَخْضَر",
        answer: "These words mean: red, white, black, green.",
        focus: word("أَخْضَر", "akhdar", "green", "سبز"),
        hook: word("سُنْدُسٍ خُضْر", "sundusin khudr", "green silk", "سبز ریشم"),
        explanationEn: "Color words are memorable and useful. They also help you practice adjective sounds early.",
        explanationUr: "رنگوں کے الفاظ یاد رہنے والے اور مفید ہوتے ہیں۔ یہ آپ کو ابتدائی صفتی آوازوں کی مشق بھی دیتے ہیں۔",
        quranicExample: word("أَبْيَض", "abyad", "white", "سفید"),
        conversationExample: word("السَّيَّارَةُ سَوْدَاء", "as-sayyaratu sawda'", "the car is black", "گاڑی کالی ہے"),
        reviewWords: [word("أَحْمَر", "ahmar", "red", "سرخ"), word("أَبْيَض", "abyad", "white", "سفید"), word("أَسْوَد", "aswad", "black", "کالا"), word("أَخْضَر", "akhdar", "green", "سبز")],
      }),
      quizLesson({
        title: "Review: World vocab",
        titleAr: "مراجعة مفردات العالم",
        type: "MULTIPLE_CHOICE",
        question: "Which word means 'market'?",
        questionUr: "کون سا لفظ 'بازار' کے معنی دیتا ہے؟",
        answer: "سُوق",
        options: ["بَيْت", "سُوق", "قَمَر", "نُور"],
        hook: word("سُوق", "suq", "market", "بازار"),
        focus: word("العَالَم", "al-'alam", "the world", "دنیا"),
        explanationEn: "This review mixes places, nature, and daily nouns so you learn to recall them by meaning.",
        explanationUr: "یہ دہرائی جگہوں، فطرت، اور روزمرہ کے اسماء کو ملا کر لاتی ہے تاکہ آپ معنی کے ذریعے انہیں یاد کریں۔",
        quranicExample: word("أَرْض", "ard", "earth", "زمین"),
        conversationExample: word("أُرِيدُ الذَّهَابَ إِلَى السُّوق", "uridu adh-dhahaba ila s-suq", "I want to go to the market", "میں بازار جانا چاہتا ہوں"),
        reviewWords: [word("سُوق", "suq", "market", "بازار"), word("نُور", "nur", "light", "نور")],
      }),
    ]
  ),
  chapter(
    9,
    "Action Words (Basic Verbs)",
    "الأفعال الأساسية",
    "Madinah · Meet common motion, speech, perception, and daily-life verbs.",
    0.64,
    0.36,
    [
      flashcardLesson({
        title: "To go & come",
        titleAr: "ذهب وجاء",
        prompt: "ذَهَبَ • جَاءَ",
        answer: "These verbs mean: to go, to come.",
        focus: word("ذَهَبَ", "dhahaba", "he went", "وہ گیا"),
        hook: word("جَاءَ الحَقُّ", "ja'a al-haqqu", "the truth came", "حق آ گیا"),
        explanationEn: "Movement verbs are some of the most useful verbs in any language. Start with go and come because they appear in both stories and daily speech.",
        explanationUr: "حرکت کے افعال ہر زبان میں بہت مفید ہوتے ہیں۔ جانے اور آنے سے آغاز کریں کیونکہ یہ قصوں اور روزمرہ گفتگو دونوں میں آتے ہیں۔",
        quranicExample: word("جَاءَ", "ja'a", "he came", "وہ آیا"),
        conversationExample: word("ذَهَبْتُ إِلَى المَسْجِد", "dhahabtu ila al-masjid", "I went to the mosque", "میں مسجد گیا"),
        reviewWords: [word("ذَهَبَ", "dhahaba", "went", "گیا"), word("جَاءَ", "ja'a", "came", "آیا")],
      }),
      flashcardLesson({
        title: "To say & hear",
        titleAr: "قال وسمع",
        prompt: "قَالَ • سَمِعَ",
        answer: "These verbs mean: to say, to hear.",
        focus: word("قَالَ", "qala", "he said", "اس نے کہا"),
        hook: word("قَالَ اللّٰهُ", "qala Allahu", "Allah said", "اللہ نے فرمایا"),
        explanationEn: "These two verbs carry meaning in nearly every story and every conversation: one produces speech, the other receives it.",
        explanationUr: "یہ دونوں افعال تقریباً ہر قصے اور گفتگو میں معنی اٹھاتے ہیں: ایک بولنے کے لیے اور دوسرا سننے کے لیے۔",
        quranicExample: word("سَمِعَ", "sami'a", "he heard", "اس نے سنا"),
        conversationExample: word("قُلْتُ لَهُ", "qultu lahu", "I said to him", "میں نے اس سے کہا"),
        reviewWords: [word("قَالَ", "qala", "said", "کہا"), word("سَمِعَ", "sami'a", "heard", "سنا")],
      }),
      flashcardLesson({
        title: "To see & know",
        titleAr: "رأى وعلم",
        prompt: "رَأَى • عَلِمَ",
        answer: "These verbs mean: to see, to know.",
        focus: word("عَلِمَ", "'alima", "he knew", "وہ جانا / اسے معلوم ہوا"),
        hook: word("أَلَمْ تَرَ", "alam tara", "have you not seen", "کیا تم نے نہیں دیکھا"),
        explanationEn: "These are perception verbs. One is for seeing with the eyes, the other for knowing with the mind.",
        explanationUr: "یہ ادراک کے افعال ہیں۔ ایک آنکھ سے دیکھنے کے لیے ہے اور دوسرا ذہن سے جاننے کے لیے۔",
        quranicExample: word("عَلِيم", "'alim", "all-knowing", "سب جاننے والا"),
        conversationExample: word("أَعْلَمُ الجَوَاب", "a'lamu al-jawab", "I know the answer", "میں جواب جانتا ہوں"),
        reviewWords: [word("رَأَى", "ra'a", "saw", "دیکھا"), word("عَلِمَ", "'alima", "knew", "جانا")],
      }),
      flashcardLesson({
        title: "To do & make",
        titleAr: "فعل وعمل",
        prompt: "فَعَلَ • عَمِلَ",
        answer: "These verbs mean: to do, to work / act.",
        focus: word("فَعَلَ", "fa'ala", "he did", "اس نے کیا"),
        hook: word("كَيْفَ فَعَلَ رَبُّكَ", "kayfa fa'ala rabbuka", "how your Lord dealt", "تمہارے رب نے کیا کیا"),
        explanationEn: "These action verbs are closely related, but 'amila often carries the sense of working or acting repeatedly.",
        explanationUr: "یہ دونوں عمل والے افعال ہیں، مگر عَمِلَ میں کام کرنے یا مسلسل عمل کرنے کا رنگ زیادہ ہوتا ہے۔",
        quranicExample: word("عَمِلُوا الصَّالِحَات", "'amilu s-salihat", "they did righteous deeds", "انہوں نے نیک اعمال کیے"),
        conversationExample: word("مَاذَا فَعَلْتَ؟", "madha fa'alta?", "what did you do?", "تم نے کیا کیا؟"),
        reviewWords: [word("فَعَلَ", "fa'ala", "did", "کیا"), word("عَمِلَ", "'amila", "worked / acted", "عمل کیا")],
      }),
      flashcardLesson({
        title: "To enter & exit",
        titleAr: "دخل وخرج",
        prompt: "دَخَلَ • خَرَجَ",
        answer: "These verbs mean: to enter, to exit.",
        focus: word("دَخَلَ", "dakhala", "he entered", "وہ داخل ہوا"),
        hook: word("ادْخُلُوهَا بِسَلَام", "udkhuluha bisalam", "enter it in peace", "اس میں سلامتی کے ساتھ داخل ہو"),
        explanationEn: "These location verbs are practical and easy to visualize, which makes them excellent memory anchors.",
        explanationUr: "یہ جگہ سے متعلق افعال عملی بھی ہیں اور آسانی سے ذہن میں تصویر بھی بناتے ہیں، اس لیے جلد یاد رہتے ہیں۔",
        quranicExample: word("خَرَجَ", "kharaja", "he exited", "وہ نکلا"),
        conversationExample: word("خَرَجْتُ مِنَ البَيْت", "kharajtu mina al-bayt", "I left the house", "میں گھر سے نکلا"),
        reviewWords: [word("دَخَلَ", "dakhala", "entered", "داخل ہوا"), word("خَرَجَ", "kharaja", "left", "نکلا")],
      }),
      flashcardLesson({
        title: "To eat & drink",
        titleAr: "أكل وشرب",
        prompt: "أَكَلَ • شَرِبَ",
        answer: "These verbs mean: to eat, to drink.",
        focus: word("أَكَلَ", "akala", "he ate", "اس نے کھایا"),
        hook: word("كُلُوا وَاشْرَبُوا", "kulu wa-shrabu", "eat and drink", "کھاؤ اور پیو"),
        explanationEn: "Daily life verbs stick quickly because you can use them immediately in simple sentences.",
        explanationUr: "روزمرہ کے افعال جلد یاد ہو جاتے ہیں کیونکہ آپ انہیں فوراً سادہ جملوں میں استعمال کر سکتے ہیں۔",
        quranicExample: word("اشْرَبُوا", "ishrabu", "drink", "پیو"),
        conversationExample: word("أَكَلْتُ خُبْزًا", "akaltu khubzan", "I ate bread", "میں نے روٹی کھائی"),
        reviewWords: [word("أَكَلَ", "akala", "ate", "کھایا"), word("شَرِبَ", "shariba", "drank", "پیا")],
      }),
      quizLesson({
        title: "Review: Verbs",
        titleAr: "مراجعة الأفعال",
        type: "FILL_BLANK",
        question: "Which verb means 'he entered'?",
        questionUr: "کون سا فعل 'وہ داخل ہوا' کے معنی دیتا ہے؟",
        answer: "دَخَلَ",
        options: ["خَرَجَ", "دَخَلَ", "شَرِبَ", "قَالَ"],
        hook: word("دَخَلَ", "dakhala", "he entered", "وہ داخل ہوا"),
        focus: word("الفعل", "al-fi'l", "the verb", "فعل"),
        explanationEn: "This review checks whether the core meaning of each beginner verb is settling into memory.",
        explanationUr: "یہ دہرائی دیکھتی ہے کہ بنیادی افعال کے معنی آپ کے ذہن میں مضبوط ہو رہے ہیں یا نہیں۔",
        quranicExample: word("جَاءَ", "ja'a", "came", "آیا"),
        conversationExample: word("ذَهَبْتُ", "dhahabtu", "I went", "میں گیا"),
        reviewWords: [word("دَخَلَ", "dakhala", "entered", "داخل ہوا"), word("خَرَجَ", "kharaja", "left", "نکلا")],
      }),
    ]
  ),
  chapter(
    10,
    "Descriptive Words (Adjectives)",
    "الصفات",
    "Madinah · End Phase 1.5 with simple adjectives you can attach to nouns in Quranic and everyday Arabic.",
    0.7,
    0.4,
    [
      flashcardLesson({
        title: "Big & Small",
        titleAr: "كبير وصغير",
        prompt: "كَبِير • صَغِير",
        answer: "These adjectives mean: big, small.",
        focus: word("كَبِير", "kabir", "big", "بڑا"),
        hook: word("اللّٰهُ أَكْبَر", "Allahu Akbar", "Allah is greater", "اللہ سب سے بڑا ہے"),
        explanationEn: "Adjectives describe nouns. Start with size because it works naturally in both Quranic imagery and daily conversation.",
        explanationUr: "صفات اسم کی حالت بتاتی ہیں۔ بڑے اور چھوٹے سے آغاز کریں کیونکہ یہ قرآن اور روزمرہ گفتگو دونوں میں آسانی سے آتے ہیں۔",
        quranicExample: word("أَجْرٌ كَبِير", "ajrun kabir", "a great reward", "بڑا اجر"),
        conversationExample: word("بَيْتٌ صَغِير", "baytun saghir", "a small house", "ایک چھوٹا گھر"),
        reviewWords: [word("كَبِير", "kabir", "big", "بڑا"), word("صَغِير", "saghir", "small", "چھوٹا")],
      }),
      flashcardLesson({
        title: "Good & Bad",
        titleAr: "حسن وسيّئ",
        prompt: "حَسَن • سَيِّئ",
        answer: "These adjectives mean: good, bad.",
        focus: word("حَسَن", "hasan", "good", "اچھا"),
        hook: word("جَزَاءً حَسَنًا", "jaza'an hasanan", "a good reward", "اچھا بدلہ"),
        explanationEn: "These are strong value words. Use them to describe actions, character, and outcomes.",
        explanationUr: "یہ قدر اور معیار بتانے والے الفاظ ہیں۔ ان سے آپ اعمال، اخلاق، اور نتائج کو بیان کر سکتے ہیں۔",
        quranicExample: word("حَسَنَة", "hasanah", "good deed", "نیکی"),
        conversationExample: word("هٰذَا كِتَابٌ حَسَن", "hadha kitabun hasan", "this is a good book", "یہ اچھی کتاب ہے"),
        reviewWords: [word("حَسَن", "hasan", "good", "اچھا"), word("سَيِّئ", "sayyi'", "bad", "برا")],
      }),
      flashcardLesson({
        title: "New & Old",
        titleAr: "جديد وقديم",
        prompt: "جَدِيد • قَدِيم",
        answer: "These adjectives mean: new, old.",
        focus: word("جَدِيد", "jadid", "new", "نیا"),
        hook: word("ثَوْبٌ جَدِيد", "thawbun jadid", "a new garment", "نیا لباس"),
        explanationEn: "These time-related adjectives help you compare objects and talk about change.",
        explanationUr: "یہ وقت سے متعلق صفات ہیں جو چیزوں کا موازنہ اور تبدیلی بیان کرنے میں مدد دیتی ہیں۔",
        quranicExample: word("قَدِيم", "qadim", "old", "پرانا"),
        conversationExample: word("هٰذِهِ سَيَّارَةٌ جَدِيدَة", "hadhihi sayyaratun jadidah", "this is a new car", "یہ نئی گاڑی ہے"),
        reviewWords: [word("جَدِيد", "jadid", "new", "نیا"), word("قَدِيم", "qadim", "old", "پرانا")],
      }),
      flashcardLesson({
        title: "Near & Far",
        titleAr: "قريب وبعيد",
        prompt: "قَرِيب • بَعِيد",
        answer: "These adjectives mean: near, far.",
        focus: word("قَرِيب", "qarib", "near", "قریب"),
        hook: word("إِنَّ رَحْمَتَ اللّٰهِ قَرِيب", "inna rahmata Allahi qarib", "Indeed the mercy of Allah is near", "بیشک اللہ کی رحمت قریب ہے"),
        explanationEn: "These describe distance and work especially well with location words you already learned.",
        explanationUr: "یہ فاصلے کو بیان کرتی ہیں اور آپ کی سیکھی ہوئی جگہوں کے الفاظ کے ساتھ اچھی طرح جڑتی ہیں۔",
        quranicExample: word("بَعِيد", "ba'id", "far", "دور"),
        conversationExample: word("المَسْجِدُ قَرِيب", "al-masjidu qarib", "the mosque is near", "مسجد قریب ہے"),
        reviewWords: [word("قَرِيب", "qarib", "near", "قریب"), word("بَعِيد", "ba'id", "far", "دور")],
      }),
      flashcardLesson({
        title: "Beautiful & Difficult",
        titleAr: "جميل وصعب",
        prompt: "جَمِيل • صَعْب",
        answer: "These adjectives mean: beautiful, difficult.",
        focus: word("جَمِيل", "jamil", "beautiful", "خوبصورت"),
        hook: word("صَبْرٌ جَمِيل", "sabrun jamil", "beautiful patience", "خوبصورت صبر"),
        explanationEn: "One adjective helps you appreciate beauty, while the other helps you talk honestly about challenge and effort.",
        explanationUr: "ایک صفت خوبصورتی کو بیان کرتی ہے اور دوسری مشکل اور محنت کے بارے میں بات کرنے میں مدد دیتی ہے۔",
        quranicExample: word("صَبْرٌ جَمِيل", "sabrun jamil", "beautiful patience", "خوبصورت صبر"),
        conversationExample: word("العَرَبِيَّةُ جَمِيلَةٌ وَلٰكِنَّهَا صَعْبَةٌ", "al-'arabiyyatu جميلah walakinnaha sa'bah", "Arabic is beautiful but difficult", "عربی خوبصورت ہے لیکن مشکل ہے"),
        reviewWords: [word("جَمِيل", "jamil", "beautiful", "خوبصورت"), word("صَعْب", "sa'b", "difficult", "مشکل")],
      }),
      quizLesson({
        title: "Review: Adjectives",
        titleAr: "مراجعة الصفات",
        type: "MULTIPLE_CHOICE",
        question: "Which adjective means 'green'?",
        questionUr: "کون سی صفت 'سبز' کے معنی دیتی ہے؟",
        answer: "أَخْضَر",
        options: ["أَخْضَر", "قَدِيم", "صَغِير", "صَعْب"],
        hook: word("أَخْضَر", "akhdar", "green", "سبز"),
        focus: word("الصفة", "as-sifah", "the adjective", "صفت"),
        explanationEn: "This review blends new adjectives with older color vocabulary to strengthen descriptive recall.",
        explanationUr: "یہ دہرائی نئی صفات کو پہلے سیکھے گئے رنگوں کے ساتھ ملا کر بیان کرنے کی قوت مضبوط کرتی ہے۔",
        quranicExample: word("جَنَّاتٍ خُضْر", "jannatin khudr", "green gardens", "سبز باغات"),
        conversationExample: word("كِتَابٌ جَدِيد", "kitabun jadid", "a new book", "نئی کتاب"),
        reviewWords: [word("أَخْضَر", "akhdar", "green", "سبز"), word("جَدِيد", "jadid", "new", "نیا"), word("صَعْب", "sa'b", "difficult", "مشکل")],
      }),
    ]
  ),
];

module.exports = {
  chapters,
};
