// Vocabulary Bank seed — 80 curated words across 16 topic categories
// 5 words per topic, each with full linguistic data

const VOCABULARY_WORDS = [
  // ── النَّاس — People ─────────────────────────────────────────────────────────
  {
    arabic: "رَجُل", arabicPlain: "رجل", transliteration: "rajul",
    translationEn: "man", translationUr: "مرد",
    wordType: "NOUN", gender: "MASCULINE", pluralForm: "رِجَال",
    rootLetters: "ر ج ل", topicCategories: ["people"], chapterIntroduced: 1,
    frequencyInQuran: 73, sortOrder: 1,
    quranicExample: null,
  },
  {
    arabic: "امْرَأَة", arabicPlain: "امراة", transliteration: "imra'a",
    translationEn: "woman", translationUr: "عورت",
    wordType: "NOUN", gender: "FEMININE", pluralForm: "نِسَاء",
    rootLetters: "م ر أ", topicCategories: ["people"], chapterIntroduced: 1,
    frequencyInQuran: 26, sortOrder: 2,
    quranicExample: null,
  },
  {
    arabic: "وَلَد", arabicPlain: "ولد", transliteration: "walad",
    translationEn: "boy, child", translationUr: "لڑکا، بچہ",
    wordType: "NOUN", gender: "MASCULINE", pluralForm: "أَوْلَاد",
    rootLetters: "و ل د", topicCategories: ["people", "family"], chapterIntroduced: 1,
    frequencyInQuran: 100, sortOrder: 3,
    quranicExample: null,
  },
  {
    arabic: "بِنْت", arabicPlain: "بنت", transliteration: "bint",
    translationEn: "girl, daughter", translationUr: "لڑکی، بیٹی",
    wordType: "NOUN", gender: "FEMININE", pluralForm: "بَنَات",
    rootLetters: "ب ن ت", topicCategories: ["people", "family"], chapterIntroduced: 1,
    frequencyInQuran: 18, sortOrder: 4,
    quranicExample: null,
  },
  {
    arabic: "نَاس", arabicPlain: "ناس", transliteration: "nās",
    translationEn: "people, mankind", translationUr: "لوگ، انسان",
    wordType: "NOUN", gender: "MASCULINE", pluralForm: null,
    rootLetters: "أ ن س", topicCategories: ["people"], chapterIntroduced: 1,
    frequencyInQuran: 241, sortOrder: 5,
    quranicExample: {
      surahNumber: 114, surahNameAr: "النَّاس", surahNameEn: "An-Nas",
      ayahNumber: 1, ayahArabic: "قُلْ أَعُوذُ بِرَبِّ النَّاسِ",
      wordPosition: 4,
      translationEn: "Say: I seek refuge in the Lord of mankind",
      translationUr: "کہو: میں پناہ مانگتا ہوں لوگوں کے رب کی",
    },
  },

  // ── العَائِلَة — Family ──────────────────────────────────────────────────────
  {
    arabic: "أَب", arabicPlain: "اب", transliteration: "ab",
    translationEn: "father", translationUr: "باپ",
    wordType: "NOUN", gender: "MASCULINE", pluralForm: "آبَاء",
    rootLetters: "أ ب و", topicCategories: ["family"], chapterIntroduced: 1,
    frequencyInQuran: 118, sortOrder: 6,
    quranicExample: null,
  },
  {
    arabic: "أُمّ", arabicPlain: "ام", transliteration: "umm",
    translationEn: "mother", translationUr: "ماں",
    wordType: "NOUN", gender: "FEMININE", pluralForm: "أُمَّهَات",
    rootLetters: "أ م م", topicCategories: ["family"], chapterIntroduced: 1,
    frequencyInQuran: 113, sortOrder: 7,
    quranicExample: null,
  },
  {
    arabic: "أَخ", arabicPlain: "اخ", transliteration: "akh",
    translationEn: "brother", translationUr: "بھائی",
    wordType: "NOUN", gender: "MASCULINE", pluralForm: "إِخْوَة",
    rootLetters: "أ خ و", topicCategories: ["family"], chapterIntroduced: 1,
    frequencyInQuran: 96, sortOrder: 8,
    quranicExample: null,
  },
  {
    arabic: "أُخْت", arabicPlain: "اخت", transliteration: "ukht",
    translationEn: "sister", translationUr: "بہن",
    wordType: "NOUN", gender: "FEMININE", pluralForm: "أَخَوَات",
    rootLetters: "أ خ و", topicCategories: ["family"], chapterIntroduced: 1,
    frequencyInQuran: 30, sortOrder: 9,
    quranicExample: null,
  },
  {
    arabic: "ابْن", arabicPlain: "ابن", transliteration: "ibn",
    translationEn: "son", translationUr: "بیٹا",
    wordType: "NOUN", gender: "MASCULINE", pluralForm: "أَبْنَاء",
    rootLetters: "ب ن و", topicCategories: ["family"], chapterIntroduced: 1,
    frequencyInQuran: 162, sortOrder: 10,
    quranicExample: null,
  },

  // ── الجِسْم — Body ───────────────────────────────────────────────────────────
  {
    arabic: "يَد", arabicPlain: "يد", transliteration: "yad",
    translationEn: "hand", translationUr: "ہاتھ",
    wordType: "NOUN", gender: "FEMININE", pluralForm: "أَيْدِي",
    rootLetters: "ي د و", topicCategories: ["body"], chapterIntroduced: 2,
    frequencyInQuran: 120, sortOrder: 11,
    quranicExample: null,
  },
  {
    arabic: "عَيْن", arabicPlain: "عين", transliteration: "'ayn",
    translationEn: "eye", translationUr: "آنکھ",
    wordType: "NOUN", gender: "FEMININE", pluralForm: "أَعْيُن",
    rootLetters: "ع ي ن", topicCategories: ["body"], chapterIntroduced: 2,
    frequencyInQuran: 56, sortOrder: 12,
    quranicExample: null,
  },
  {
    arabic: "رَأْس", arabicPlain: "راس", transliteration: "ra's",
    translationEn: "head", translationUr: "سر",
    wordType: "NOUN", gender: "MASCULINE", pluralForm: "رُءُوس",
    rootLetters: "ر أ س", topicCategories: ["body"], chapterIntroduced: 2,
    frequencyInQuran: 18, sortOrder: 13,
    quranicExample: null,
  },
  {
    arabic: "قَلْب", arabicPlain: "قلب", transliteration: "qalb",
    translationEn: "heart", translationUr: "دل",
    wordType: "NOUN", gender: "MASCULINE", pluralForm: "قُلُوب",
    rootLetters: "ق ل ب", topicCategories: ["body"], chapterIntroduced: 2,
    frequencyInQuran: 168, sortOrder: 14,
    quranicExample: {
      surahNumber: 2, surahNameAr: "البَقَرَة", surahNameEn: "Al-Baqarah",
      ayahNumber: 7, ayahArabic: "خَتَمَ اللَّهُ عَلَىٰ قُلُوبِهِمْ",
      wordPosition: 3,
      translationEn: "Allah has set a seal on their hearts",
      translationUr: "اللہ نے ان کے دلوں پر مہر لگا دی",
    },
  },
  {
    arabic: "وَجْه", arabicPlain: "وجه", transliteration: "wajh",
    translationEn: "face", translationUr: "چہرہ",
    wordType: "NOUN", gender: "MASCULINE", pluralForm: "وُجُوه",
    rootLetters: "و ج ه", topicCategories: ["body"], chapterIntroduced: 2,
    frequencyInQuran: 72, sortOrder: 15,
    quranicExample: null,
  },

  // ── البَيْت — Home ───────────────────────────────────────────────────────────
  {
    arabic: "بَيْت", arabicPlain: "بيت", transliteration: "bayt",
    translationEn: "house, home", translationUr: "گھر",
    wordType: "NOUN", gender: "MASCULINE", pluralForm: "بُيُوت",
    rootLetters: "ب ي ت", topicCategories: ["home"], chapterIntroduced: 1,
    frequencyInQuran: 71, sortOrder: 16,
    quranicExample: null,
  },
  {
    arabic: "بَاب", arabicPlain: "باب", transliteration: "bāb",
    translationEn: "door, gate", translationUr: "دروازہ",
    wordType: "NOUN", gender: "MASCULINE", pluralForm: "أَبْوَاب",
    rootLetters: "ب و ب", topicCategories: ["home"], chapterIntroduced: 2,
    frequencyInQuran: 61, sortOrder: 17,
    quranicExample: null,
  },
  {
    arabic: "كُرْسِيّ", arabicPlain: "كرسي", transliteration: "kursī",
    translationEn: "chair, throne", translationUr: "کرسی",
    wordType: "NOUN", gender: "MASCULINE", pluralForm: "كَرَاسِيّ",
    rootLetters: "ك ر س", topicCategories: ["home"], chapterIntroduced: 2,
    frequencyInQuran: 1, sortOrder: 18,
    quranicExample: {
      surahNumber: 2, surahNameAr: "البَقَرَة", surahNameEn: "Al-Baqarah",
      ayahNumber: 255, ayahArabic: "وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ",
      wordPosition: 1,
      translationEn: "His Kursi (Throne) extends over the heavens and the earth",
      translationUr: "اس کی کرسی آسمانوں اور زمین پر محیط ہے",
    },
  },
  {
    arabic: "غُرْفَة", arabicPlain: "غرفة", transliteration: "ghurfa",
    translationEn: "room, chamber", translationUr: "کمرہ",
    wordType: "NOUN", gender: "FEMININE", pluralForm: "غُرَف",
    rootLetters: "غ ر ف", topicCategories: ["home"], chapterIntroduced: 2,
    frequencyInQuran: 5, sortOrder: 19,
    quranicExample: null,
  },
  {
    arabic: "مَكْتَب", arabicPlain: "مكتب", transliteration: "maktab",
    translationEn: "desk, office", translationUr: "میز، دفتر",
    wordType: "NOUN", gender: "MASCULINE", pluralForm: "مَكَاتِب",
    rootLetters: "ك ت ب", topicCategories: ["home", "school"], chapterIntroduced: 2,
    frequencyInQuran: 0, sortOrder: 20,
    quranicExample: null,
  },

  // ── الطَّعَام — Food ─────────────────────────────────────────────────────────
  {
    arabic: "مَاء", arabicPlain: "ماء", transliteration: "mā'",
    translationEn: "water", translationUr: "پانی",
    wordType: "NOUN", gender: "MASCULINE", pluralForm: "مِيَاه",
    rootLetters: "م و ه", topicCategories: ["food", "nature"], chapterIntroduced: 1,
    frequencyInQuran: 63, sortOrder: 21,
    quranicExample: {
      surahNumber: 2, surahNameAr: "البَقَرَة", surahNameEn: "Al-Baqarah",
      ayahNumber: 22, ayahArabic: "وَأَنزَلَ مِنَ السَّمَاءِ مَاءً",
      wordPosition: 4,
      translationEn: "And sent down from the sky rain",
      translationUr: "اور آسمان سے پانی اتارا",
    },
  },
  {
    arabic: "خُبْز", arabicPlain: "خبز", transliteration: "khubz",
    translationEn: "bread", translationUr: "روٹی",
    wordType: "NOUN", gender: "MASCULINE", pluralForm: null,
    rootLetters: "خ ب ز", topicCategories: ["food"], chapterIntroduced: 3,
    frequencyInQuran: 2, sortOrder: 22,
    quranicExample: null,
  },
  {
    arabic: "تَمْر", arabicPlain: "تمر", transliteration: "tamr",
    translationEn: "dates (fruit)", translationUr: "کھجور",
    wordType: "NOUN", gender: "MASCULINE", pluralForm: null,
    rootLetters: "ت م ر", topicCategories: ["food"], chapterIntroduced: 3,
    frequencyInQuran: 0, sortOrder: 23,
    quranicExample: null,
  },
  {
    arabic: "لَبَن", arabicPlain: "لبن", transliteration: "laban",
    translationEn: "milk", translationUr: "دودھ",
    wordType: "NOUN", gender: "MASCULINE", pluralForm: null,
    rootLetters: "ل ب ن", topicCategories: ["food"], chapterIntroduced: 3,
    frequencyInQuran: 5, sortOrder: 24,
    quranicExample: null,
  },
  {
    arabic: "طَعَام", arabicPlain: "طعام", transliteration: "ṭa'ām",
    translationEn: "food, meal", translationUr: "کھانا",
    wordType: "NOUN", gender: "MASCULINE", pluralForm: null,
    rootLetters: "ط ع م", topicCategories: ["food"], chapterIntroduced: 3,
    frequencyInQuran: 16, sortOrder: 25,
    quranicExample: null,
  },

  // ── الزَّمَن — Time ──────────────────────────────────────────────────────────
  {
    arabic: "يَوْم", arabicPlain: "يوم", transliteration: "yawm",
    translationEn: "day", translationUr: "دن",
    wordType: "NOUN", gender: "MASCULINE", pluralForm: "أَيَّام",
    rootLetters: "ي و م", topicCategories: ["time"], chapterIntroduced: 1,
    frequencyInQuran: 475, sortOrder: 26,
    quranicExample: {
      surahNumber: 1, surahNameAr: "الفَاتِحَة", surahNameEn: "Al-Fatiha",
      ayahNumber: 4, ayahArabic: "مَالِكِ يَوْمِ الدِّينِ",
      wordPosition: 1,
      translationEn: "Master of the Day of Judgement",
      translationUr: "بدلے کے دن کا مالک",
    },
  },
  {
    arabic: "لَيْل", arabicPlain: "ليل", transliteration: "layl",
    translationEn: "night", translationUr: "رات",
    wordType: "NOUN", gender: "MASCULINE", pluralForm: "لَيَالٍ",
    rootLetters: "ل ي ل", topicCategories: ["time"], chapterIntroduced: 2,
    frequencyInQuran: 92, sortOrder: 27,
    quranicExample: null,
  },
  {
    arabic: "سَنَة", arabicPlain: "سنة", transliteration: "sana",
    translationEn: "year", translationUr: "سال",
    wordType: "NOUN", gender: "FEMININE", pluralForm: "سِنِين",
    rootLetters: "س ن و", topicCategories: ["time"], chapterIntroduced: 3,
    frequencyInQuran: 19, sortOrder: 28,
    quranicExample: null,
  },
  {
    arabic: "سَاعَة", arabicPlain: "ساعة", transliteration: "sā'a",
    translationEn: "hour, moment", translationUr: "گھنٹہ، لمحہ",
    wordType: "NOUN", gender: "FEMININE", pluralForm: "سَاعَات",
    rootLetters: "س و ع", topicCategories: ["time"], chapterIntroduced: 3,
    frequencyInQuran: 48, sortOrder: 29,
    quranicExample: null,
  },
  {
    arabic: "وَقْت", arabicPlain: "وقت", transliteration: "waqt",
    translationEn: "time, appointed time", translationUr: "وقت",
    wordType: "NOUN", gender: "MASCULINE", pluralForm: "أَوْقَات",
    rootLetters: "و ق ت", topicCategories: ["time"], chapterIntroduced: 2,
    frequencyInQuran: 13, sortOrder: 30,
    quranicExample: null,
  },

  // ── الطَّبِيعَة — Nature ─────────────────────────────────────────────────────
  {
    arabic: "سَمَاء", arabicPlain: "سماء", transliteration: "samā'",
    translationEn: "sky, heaven", translationUr: "آسمان",
    wordType: "NOUN", gender: "FEMININE", pluralForm: "سَمَاوَات",
    rootLetters: "س م و", topicCategories: ["nature"], chapterIntroduced: 1,
    frequencyInQuran: 392, sortOrder: 31,
    quranicExample: {
      surahNumber: 2, surahNameAr: "البَقَرَة", surahNameEn: "Al-Baqarah",
      ayahNumber: 22, ayahArabic: "الَّذِي جَعَلَ لَكُمُ الْأَرْضَ فِرَاشًا وَالسَّمَاءَ بِنَاءً",
      wordPosition: 7,
      translationEn: "He who made for you the earth a bed and the sky a ceiling",
      translationUr: "جس نے تمہارے لیے زمین کو بچھونا اور آسمان کو چھت بنایا",
    },
  },
  {
    arabic: "أَرْض", arabicPlain: "ارض", transliteration: "arḍ",
    translationEn: "earth, land", translationUr: "زمین",
    wordType: "NOUN", gender: "FEMININE", pluralForm: "أَرَاضٍ",
    rootLetters: "أ ر ض", topicCategories: ["nature"], chapterIntroduced: 1,
    frequencyInQuran: 461, sortOrder: 32,
    quranicExample: {
      surahNumber: 2, surahNameAr: "البَقَرَة", surahNameEn: "Al-Baqarah",
      ayahNumber: 22, ayahArabic: "الَّذِي جَعَلَ لَكُمُ الْأَرْضَ فِرَاشًا",
      wordPosition: 5,
      translationEn: "He who made for you the earth a bed",
      translationUr: "جس نے تمہارے لیے زمین کو بچھونا بنایا",
    },
  },
  {
    arabic: "شَمْس", arabicPlain: "شمس", transliteration: "shams",
    translationEn: "sun", translationUr: "سورج",
    wordType: "NOUN", gender: "FEMININE", pluralForm: null,
    rootLetters: "ش م س", topicCategories: ["nature"], chapterIntroduced: 2,
    frequencyInQuran: 33, sortOrder: 33,
    quranicExample: null,
  },
  {
    arabic: "قَمَر", arabicPlain: "قمر", transliteration: "qamar",
    translationEn: "moon", translationUr: "چاند",
    wordType: "NOUN", gender: "MASCULINE", pluralForm: "أَقْمَار",
    rootLetters: "ق م ر", topicCategories: ["nature"], chapterIntroduced: 2,
    frequencyInQuran: 27, sortOrder: 34,
    quranicExample: null,
  },
  {
    arabic: "شَجَرَة", arabicPlain: "شجرة", transliteration: "shajara",
    translationEn: "tree", translationUr: "درخت",
    wordType: "NOUN", gender: "FEMININE", pluralForm: "أَشْجَار",
    rootLetters: "ش ج ر", topicCategories: ["nature"], chapterIntroduced: 3,
    frequencyInQuran: 26, sortOrder: 35,
    quranicExample: null,
  },

  // ── العِبَادَة — Worship ─────────────────────────────────────────────────────
  {
    arabic: "صَلَاة", arabicPlain: "صلاة", transliteration: "ṣalāh",
    translationEn: "prayer", translationUr: "نماز",
    wordType: "NOUN", gender: "FEMININE", pluralForm: "صَلَوَات",
    rootLetters: "ص ل و", topicCategories: ["worship"], chapterIntroduced: 1,
    frequencyInQuran: 99, sortOrder: 36,
    quranicExample: {
      surahNumber: 2, surahNameAr: "البَقَرَة", surahNameEn: "Al-Baqarah",
      ayahNumber: 3, ayahArabic: "الَّذِينَ يُؤْمِنُونَ بِالْغَيْبِ وَيُقِيمُونَ الصَّلَاةَ",
      wordPosition: 5,
      translationEn: "Those who believe in the unseen and establish prayer",
      translationUr: "جو غیب پر ایمان لاتے اور نماز قائم کرتے ہیں",
    },
  },
  {
    arabic: "صَوْم", arabicPlain: "صوم", transliteration: "ṣawm",
    translationEn: "fasting", translationUr: "روزہ",
    wordType: "NOUN", gender: "MASCULINE", pluralForm: null,
    rootLetters: "ص و م", topicCategories: ["worship"], chapterIntroduced: 4,
    frequencyInQuran: 8, sortOrder: 37,
    quranicExample: null,
  },
  {
    arabic: "زَكَاة", arabicPlain: "زكاة", transliteration: "zakāh",
    translationEn: "obligatory charity", translationUr: "زکوٰۃ",
    wordType: "NOUN", gender: "FEMININE", pluralForm: null,
    rootLetters: "ز ك و", topicCategories: ["worship"], chapterIntroduced: 4,
    frequencyInQuran: 32, sortOrder: 38,
    quranicExample: null,
  },
  {
    arabic: "حَجّ", arabicPlain: "حج", transliteration: "ḥajj",
    translationEn: "pilgrimage", translationUr: "حج",
    wordType: "NOUN", gender: "MASCULINE", pluralForm: null,
    rootLetters: "ح ج ج", topicCategories: ["worship"], chapterIntroduced: 5,
    frequencyInQuran: 10, sortOrder: 39,
    quranicExample: null,
  },
  {
    arabic: "دُعَاء", arabicPlain: "دعاء", transliteration: "du'ā'",
    translationEn: "supplication", translationUr: "دعا",
    wordType: "NOUN", gender: "MASCULINE", pluralForm: "أَدْعِيَة",
    rootLetters: "د ع و", topicCategories: ["worship"], chapterIntroduced: 3,
    frequencyInQuran: 20, sortOrder: 40,
    quranicExample: null,
  },

  // ── مُصْطَلَحَات قُرْآنِيَّة — Quranic Terms ────────────────────────────────
  {
    arabic: "رَبّ", arabicPlain: "رب", transliteration: "rabb",
    translationEn: "Lord, Sustainer", translationUr: "رب، پالنے والا",
    wordType: "NOUN", gender: "MASCULINE", pluralForm: "أَرْبَاب",
    rootLetters: "ر ب ب", topicCategories: ["quranic", "worship"], chapterIntroduced: 1,
    frequencyInQuran: 980, sortOrder: 41,
    quranicExample: {
      surahNumber: 1, surahNameAr: "الفَاتِحَة", surahNameEn: "Al-Fatiha",
      ayahNumber: 2, ayahArabic: "الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ",
      wordPosition: 2,
      translationEn: "Praise be to Allah, Lord of the worlds",
      translationUr: "تمام تعریف اللہ کے لیے جو تمام جہانوں کا رب ہے",
    },
  },
  {
    arabic: "رَحْمَن", arabicPlain: "رحمن", transliteration: "raḥmān",
    translationEn: "Most Gracious", translationUr: "رحمٰن (بے حد رحم کرنے والا)",
    wordType: "ADJECTIVE", gender: null, pluralForm: null,
    rootLetters: "ر ح م", topicCategories: ["quranic", "worship"], chapterIntroduced: 1,
    frequencyInQuran: 57, sortOrder: 42,
    quranicExample: {
      surahNumber: 1, surahNameAr: "الفَاتِحَة", surahNameEn: "Al-Fatiha",
      ayahNumber: 3, ayahArabic: "الرَّحْمَٰنِ الرَّحِيمِ",
      wordPosition: 0,
      translationEn: "The Most Gracious, the Most Merciful",
      translationUr: "بے حد رحم کرنے والا، بار بار رحم کرنے والا",
    },
  },
  {
    arabic: "رَحِيم", arabicPlain: "رحيم", transliteration: "raḥīm",
    translationEn: "Most Merciful", translationUr: "رحیم (بار بار رحم کرنے والا)",
    wordType: "ADJECTIVE", gender: null, pluralForm: null,
    rootLetters: "ر ح م", topicCategories: ["quranic", "worship"], chapterIntroduced: 1,
    frequencyInQuran: 115, sortOrder: 43,
    quranicExample: {
      surahNumber: 1, surahNameAr: "الفَاتِحَة", surahNameEn: "Al-Fatiha",
      ayahNumber: 3, ayahArabic: "الرَّحْمَٰنِ الرَّحِيمِ",
      wordPosition: 1,
      translationEn: "The Most Gracious, the Most Merciful",
      translationUr: "بے حد رحم کرنے والا، بار بار رحم کرنے والا",
    },
  },
  {
    arabic: "نُور", arabicPlain: "نور", transliteration: "nūr",
    translationEn: "light", translationUr: "نور، روشنی",
    wordType: "NOUN", gender: "MASCULINE", pluralForm: "أَنْوَار",
    rootLetters: "ن و ر", topicCategories: ["quranic"], chapterIntroduced: 2,
    frequencyInQuran: 43, sortOrder: 44,
    quranicExample: {
      surahNumber: 24, surahNameAr: "النُّور", surahNameEn: "An-Nur",
      ayahNumber: 35, ayahArabic: "اللَّهُ نُورُ السَّمَاوَاتِ وَالْأَرْضِ",
      wordPosition: 1,
      translationEn: "Allah is the light of the heavens and the earth",
      translationUr: "اللہ آسمانوں اور زمین کا نور ہے",
    },
  },
  {
    arabic: "حَقّ", arabicPlain: "حق", transliteration: "ḥaqq",
    translationEn: "truth, right", translationUr: "حق، سچ",
    wordType: "NOUN", gender: "MASCULINE", pluralForm: "حُقُوق",
    rootLetters: "ح ق ق", topicCategories: ["quranic"], chapterIntroduced: 2,
    frequencyInQuran: 287, sortOrder: 45,
    quranicExample: null,
  },

  // ── الأَفْعَال — Verbs ───────────────────────────────────────────────────────
  {
    arabic: "قَرَأَ", arabicPlain: "قرا", transliteration: "qara'a",
    translationEn: "he read, he recited", translationUr: "اس نے پڑھا",
    wordType: "VERB_PAST", gender: null, pluralForm: null,
    rootLetters: "ق ر أ", topicCategories: ["verbs", "school"], chapterIntroduced: 1,
    frequencyInQuran: 88, sortOrder: 46,
    quranicExample: {
      surahNumber: 96, surahNameAr: "العَلَق", surahNameEn: "Al-Alaq",
      ayahNumber: 1, ayahArabic: "اقْرَأْ بِاسْمِ رَبِّكَ الَّذِي خَلَقَ",
      wordPosition: 0,
      translationEn: "Read in the name of your Lord who created",
      translationUr: "اپنے رب کے نام سے پڑھو جس نے پیدا کیا",
    },
  },
  {
    arabic: "كَتَبَ", arabicPlain: "كتب", transliteration: "kataba",
    translationEn: "he wrote", translationUr: "اس نے لکھا",
    wordType: "VERB_PAST", gender: null, pluralForm: null,
    rootLetters: "ك ت ب", topicCategories: ["verbs"], chapterIntroduced: 1,
    frequencyInQuran: 29, sortOrder: 47,
    quranicExample: null,
  },
  {
    arabic: "ذَهَبَ", arabicPlain: "ذهب", transliteration: "dhahaba",
    translationEn: "he went", translationUr: "وہ چلا گیا",
    wordType: "VERB_PAST", gender: null, pluralForm: null,
    rootLetters: "ذ ه ب", topicCategories: ["verbs"], chapterIntroduced: 2,
    frequencyInQuran: 26, sortOrder: 48,
    quranicExample: null,
  },
  {
    arabic: "جَاءَ", arabicPlain: "جاء", transliteration: "jā'a",
    translationEn: "he came", translationUr: "وہ آیا",
    wordType: "VERB_PAST", gender: null, pluralForm: null,
    rootLetters: "ج ي أ", topicCategories: ["verbs"], chapterIntroduced: 2,
    frequencyInQuran: 228, sortOrder: 49,
    quranicExample: null,
  },
  {
    arabic: "عَلِمَ", arabicPlain: "علم", transliteration: "'alima",
    translationEn: "he knew", translationUr: "اس نے جانا",
    wordType: "VERB_PAST", gender: null, pluralForm: null,
    rootLetters: "ع ل م", topicCategories: ["verbs"], chapterIntroduced: 2,
    frequencyInQuran: 382, sortOrder: 50,
    quranicExample: null,
  },

  // ── السَّفَر — Travel ────────────────────────────────────────────────────────
  {
    arabic: "سَفَر", arabicPlain: "سفر", transliteration: "safar",
    translationEn: "journey, travel", translationUr: "سفر",
    wordType: "NOUN", gender: "MASCULINE", pluralForm: "أَسْفَار",
    rootLetters: "س ف ر", topicCategories: ["travel"], chapterIntroduced: 4,
    frequencyInQuran: 12, sortOrder: 51,
    quranicExample: null,
  },
  {
    arabic: "طَرِيق", arabicPlain: "طريق", transliteration: "ṭarīq",
    translationEn: "road, path, way", translationUr: "راستہ",
    wordType: "NOUN", gender: "MASCULINE", pluralForm: "طُرُق",
    rootLetters: "ط ر ق", topicCategories: ["travel"], chapterIntroduced: 3,
    frequencyInQuran: 28, sortOrder: 52,
    quranicExample: null,
  },
  {
    arabic: "مَدِينَة", arabicPlain: "مدينة", transliteration: "madīna",
    translationEn: "city", translationUr: "شہر",
    wordType: "NOUN", gender: "FEMININE", pluralForm: "مُدُن",
    rootLetters: "د ي ن", topicCategories: ["travel"], chapterIntroduced: 3,
    frequencyInQuran: 14, sortOrder: 53,
    quranicExample: null,
  },
  {
    arabic: "بَلَد", arabicPlain: "بلد", transliteration: "balad",
    translationEn: "country, land", translationUr: "ملک، علاقہ",
    wordType: "NOUN", gender: "MASCULINE", pluralForm: "بِلَاد",
    rootLetters: "ب ل د", topicCategories: ["travel"], chapterIntroduced: 3,
    frequencyInQuran: 19, sortOrder: 54,
    quranicExample: null,
  },
  {
    arabic: "سَفِينَة", arabicPlain: "سفينة", transliteration: "safīna",
    translationEn: "ship, boat", translationUr: "کشتی، جہاز",
    wordType: "NOUN", gender: "FEMININE", pluralForm: "سُفُن",
    rootLetters: "س ف ن", topicCategories: ["travel"], chapterIntroduced: 5,
    frequencyInQuran: 4, sortOrder: 55,
    quranicExample: null,
  },

  // ── المَسْجِد — Masjid ───────────────────────────────────────────────────────
  {
    arabic: "مَسْجِد", arabicPlain: "مسجد", transliteration: "masjid",
    translationEn: "mosque", translationUr: "مسجد",
    wordType: "NOUN", gender: "MASCULINE", pluralForm: "مَسَاجِد",
    rootLetters: "س ج د", topicCategories: ["masjid", "worship"], chapterIntroduced: 2,
    frequencyInQuran: 28, sortOrder: 56,
    quranicExample: null,
  },
  {
    arabic: "إِمَام", arabicPlain: "امام", transliteration: "imām",
    translationEn: "imam, leader", translationUr: "امام",
    wordType: "NOUN", gender: "MASCULINE", pluralForm: "أَئِمَّة",
    rootLetters: "أ م م", topicCategories: ["masjid"], chapterIntroduced: 4,
    frequencyInQuran: 12, sortOrder: 57,
    quranicExample: null,
  },
  {
    arabic: "صَفّ", arabicPlain: "صف", transliteration: "ṣaff",
    translationEn: "row, rank (in prayer)", translationUr: "صف",
    wordType: "NOUN", gender: "MASCULINE", pluralForm: "صُفُوف",
    rootLetters: "ص ف ف", topicCategories: ["masjid"], chapterIntroduced: 4,
    frequencyInQuran: 10, sortOrder: 58,
    quranicExample: null,
  },
  {
    arabic: "قِبْلَة", arabicPlain: "قبلة", transliteration: "qibla",
    translationEn: "prayer direction (toward Makkah)", translationUr: "قبلہ",
    wordType: "NOUN", gender: "FEMININE", pluralForm: null,
    rootLetters: "ق ب ل", topicCategories: ["masjid", "worship"], chapterIntroduced: 4,
    frequencyInQuran: 4, sortOrder: 59,
    quranicExample: null,
  },
  {
    arabic: "أَذَان", arabicPlain: "اذان", transliteration: "adhān",
    translationEn: "call to prayer", translationUr: "اذان",
    wordType: "NOUN", gender: "MASCULINE", pluralForm: null,
    rootLetters: "أ ذ ن", topicCategories: ["masjid", "worship"], chapterIntroduced: 3,
    frequencyInQuran: 2, sortOrder: 60,
    quranicExample: null,
  },

  // ── السُّوق — Marketplace ────────────────────────────────────────────────────
  {
    arabic: "سُوق", arabicPlain: "سوق", transliteration: "sūq",
    translationEn: "market, bazaar", translationUr: "بازار",
    wordType: "NOUN", gender: "MASCULINE", pluralForm: "أَسْوَاق",
    rootLetters: "س و ق", topicCategories: ["marketplace"], chapterIntroduced: 5,
    frequencyInQuran: 2, sortOrder: 61,
    quranicExample: null,
  },
  {
    arabic: "بَيْع", arabicPlain: "بيع", transliteration: "bay'",
    translationEn: "sale, selling", translationUr: "بیچنا، سودا",
    wordType: "NOUN", gender: "MASCULINE", pluralForm: null,
    rootLetters: "ب ي ع", topicCategories: ["marketplace"], chapterIntroduced: 5,
    frequencyInQuran: 9, sortOrder: 62,
    quranicExample: null,
  },
  {
    arabic: "شِرَاء", arabicPlain: "شراء", transliteration: "shirā'",
    translationEn: "purchase, buying", translationUr: "خریدنا",
    wordType: "NOUN", gender: "MASCULINE", pluralForm: null,
    rootLetters: "ش ر ي", topicCategories: ["marketplace"], chapterIntroduced: 5,
    frequencyInQuran: 6, sortOrder: 63,
    quranicExample: null,
  },
  {
    arabic: "ثَمَن", arabicPlain: "ثمن", transliteration: "thaman",
    translationEn: "price, value", translationUr: "قیمت",
    wordType: "NOUN", gender: "MASCULINE", pluralForm: "أَثْمَان",
    rootLetters: "ث م ن", topicCategories: ["marketplace"], chapterIntroduced: 5,
    frequencyInQuran: 10, sortOrder: 64,
    quranicExample: null,
  },
  {
    arabic: "مَال", arabicPlain: "مال", transliteration: "māl",
    translationEn: "wealth, property", translationUr: "مال، دولت",
    wordType: "NOUN", gender: "MASCULINE", pluralForm: "أَمْوَال",
    rootLetters: "م و ل", topicCategories: ["marketplace"], chapterIntroduced: 4,
    frequencyInQuran: 86, sortOrder: 65,
    quranicExample: null,
  },

  // ── المَدْرَسَة — School ─────────────────────────────────────────────────────
  {
    arabic: "مُعَلِّم", arabicPlain: "معلم", transliteration: "mu'allim",
    translationEn: "teacher", translationUr: "استاد",
    wordType: "NOUN", gender: "MASCULINE", pluralForm: "مُعَلِّمُون",
    rootLetters: "ع ل م", topicCategories: ["school"], chapterIntroduced: 3,
    frequencyInQuran: 0, sortOrder: 66,
    quranicExample: null,
  },
  {
    arabic: "طَالِب", arabicPlain: "طالب", transliteration: "ṭālib",
    translationEn: "student, seeker", translationUr: "طالب علم",
    wordType: "NOUN", gender: "MASCULINE", pluralForm: "طُلَّاب",
    rootLetters: "ط ل ب", topicCategories: ["school"], chapterIntroduced: 3,
    frequencyInQuran: 28, sortOrder: 67,
    quranicExample: null,
  },
  {
    arabic: "قَلَم", arabicPlain: "قلم", transliteration: "qalam",
    translationEn: "pen", translationUr: "قلم",
    wordType: "NOUN", gender: "MASCULINE", pluralForm: "أَقْلَام",
    rootLetters: "ق ل م", topicCategories: ["school"], chapterIntroduced: 1,
    frequencyInQuran: 4, sortOrder: 68,
    quranicExample: {
      surahNumber: 96, surahNameAr: "العَلَق", surahNameEn: "Al-Alaq",
      ayahNumber: 4, ayahArabic: "الَّذِي عَلَّمَ بِالْقَلَمِ",
      wordPosition: 2,
      translationEn: "Who taught by the pen",
      translationUr: "جس نے قلم کے ذریعے سکھایا",
    },
  },
  {
    arabic: "كِتَاب", arabicPlain: "كتاب", transliteration: "kitāb",
    translationEn: "book", translationUr: "کتاب",
    wordType: "NOUN", gender: "MASCULINE", pluralForm: "كُتُب",
    rootLetters: "ك ت ب", topicCategories: ["school", "quranic"], chapterIntroduced: 1,
    frequencyInQuran: 230, sortOrder: 69,
    quranicExample: {
      surahNumber: 2, surahNameAr: "البَقَرَة", surahNameEn: "Al-Baqarah",
      ayahNumber: 2, ayahArabic: "ذَٰلِكَ الْكِتَابُ لَا رَيْبَ فِيهِ",
      wordPosition: 1,
      translationEn: "This is the Book about which there is no doubt",
      translationUr: "یہ وہ کتاب ہے جس میں کوئی شک نہیں",
    },
  },
  {
    arabic: "دَرْس", arabicPlain: "درس", transliteration: "dars",
    translationEn: "lesson, study", translationUr: "سبق",
    wordType: "NOUN", gender: "MASCULINE", pluralForm: "دُرُوس",
    rootLetters: "د ر س", topicCategories: ["school"], chapterIntroduced: 2,
    frequencyInQuran: 3, sortOrder: 70,
    quranicExample: null,
  },

  // ── الأَعْدَاد — Numbers ─────────────────────────────────────────────────────
  {
    arabic: "وَاحِد", arabicPlain: "واحد", transliteration: "wāḥid",
    translationEn: "one", translationUr: "ایک",
    wordType: "NUMBER", gender: "MASCULINE", pluralForm: null,
    rootLetters: "و ح د", topicCategories: ["numbers"], chapterIntroduced: 1,
    frequencyInQuran: 22, sortOrder: 71,
    quranicExample: null,
  },
  {
    arabic: "اثْنَان", arabicPlain: "اثنان", transliteration: "ithnān",
    translationEn: "two", translationUr: "دو",
    wordType: "NUMBER", gender: "MASCULINE", pluralForm: null,
    rootLetters: "ث ن ي", topicCategories: ["numbers"], chapterIntroduced: 2,
    frequencyInQuran: 16, sortOrder: 72,
    quranicExample: null,
  },
  {
    arabic: "ثَلَاثَة", arabicPlain: "ثلاثة", transliteration: "thalātha",
    translationEn: "three", translationUr: "تین",
    wordType: "NUMBER", gender: "FEMININE", pluralForm: null,
    rootLetters: "ث ل ث", topicCategories: ["numbers"], chapterIntroduced: 2,
    frequencyInQuran: 22, sortOrder: 73,
    quranicExample: null,
  },
  {
    arabic: "أَرْبَعَة", arabicPlain: "اربعة", transliteration: "arba'a",
    translationEn: "four", translationUr: "چار",
    wordType: "NUMBER", gender: "FEMININE", pluralForm: null,
    rootLetters: "ر ب ع", topicCategories: ["numbers"], chapterIntroduced: 2,
    frequencyInQuran: 12, sortOrder: 74,
    quranicExample: null,
  },
  {
    arabic: "خَمْسَة", arabicPlain: "خمسة", transliteration: "khamsa",
    translationEn: "five", translationUr: "پانچ",
    wordType: "NUMBER", gender: "FEMININE", pluralForm: null,
    rootLetters: "خ م س", topicCategories: ["numbers"], chapterIntroduced: 2,
    frequencyInQuran: 4, sortOrder: 75,
    quranicExample: null,
  },

  // ── الأَلْوَان — Colors ──────────────────────────────────────────────────────
  {
    arabic: "أَبْيَض", arabicPlain: "ابيض", transliteration: "abyaḍ",
    translationEn: "white", translationUr: "سفید",
    wordType: "ADJECTIVE", gender: "MASCULINE", pluralForm: "بِيض",
    rootLetters: "ب ي ض", topicCategories: ["colors"], chapterIntroduced: 4,
    frequencyInQuran: 11, sortOrder: 76,
    quranicExample: null,
  },
  {
    arabic: "أَسْوَد", arabicPlain: "اسود", transliteration: "aswad",
    translationEn: "black", translationUr: "کالا",
    wordType: "ADJECTIVE", gender: "MASCULINE", pluralForm: "سُود",
    rootLetters: "س و د", topicCategories: ["colors"], chapterIntroduced: 4,
    frequencyInQuran: 7, sortOrder: 77,
    quranicExample: null,
  },
  {
    arabic: "أَحْمَر", arabicPlain: "احمر", transliteration: "aḥmar",
    translationEn: "red", translationUr: "لال",
    wordType: "ADJECTIVE", gender: "MASCULINE", pluralForm: "حُمْر",
    rootLetters: "ح م ر", topicCategories: ["colors"], chapterIntroduced: 4,
    frequencyInQuran: 2, sortOrder: 78,
    quranicExample: null,
  },
  {
    arabic: "أَخْضَر", arabicPlain: "اخضر", transliteration: "akhḍar",
    translationEn: "green", translationUr: "سبز",
    wordType: "ADJECTIVE", gender: "MASCULINE", pluralForm: "خُضْر",
    rootLetters: "خ ض ر", topicCategories: ["colors"], chapterIntroduced: 4,
    frequencyInQuran: 8, sortOrder: 79,
    quranicExample: null,
  },
  {
    arabic: "أَصْفَر", arabicPlain: "اصفر", transliteration: "aṣfar",
    translationEn: "yellow", translationUr: "پیلا",
    wordType: "ADJECTIVE", gender: "MASCULINE", pluralForm: "صُفْر",
    rootLetters: "ص ف ر", topicCategories: ["colors"], chapterIntroduced: 4,
    frequencyInQuran: 4, sortOrder: 80,
    quranicExample: null,
  },
];

async function seedVocabulary(prisma) {
  await prisma.vocabularyWord.deleteMany({});
  await prisma.vocabularyWord.createMany({ data: VOCABULARY_WORDS });
  console.log(`Seeded ${VOCABULARY_WORDS.length} vocabulary words.`);
}

module.exports = { seedVocabulary };
